### ISSUE TITLE
自定义图标位置会闪退

### ISSUE THREAD

**Issue by jcs233** [Block-Network/StatusBarLyric#145]
**环境信息**

模块版本: 4.0.0
MIUI版本: 
Android版本12: 
屏幕类型: 全面屏

**在最新的release版本中能否复现**

能

**bug内容**

在自定义图标上下位置时会导致模块闪退
**复现方法**

模块设置-自定义-图标上下位置-滑动或者输入数值会导致模块闪退

**Comment by xiaowine** [comment]
> **环境信息**
> 
> 模块版本: 4.0.0 MIUI版本: Android版本12: 屏幕类型: 全面屏
> 
> **在最新的release版本中能否复现**
> 
> 能
> 
> **bug内容**
> 
> 在自定义图标上下位置时会导致模块闪退 **复现方法**
> 
> 模块设置-自定义-图标上下位置-滑动或者输入数值会导致模块闪退

测试版已经修复
