### ISSUE TITLE
增加对dso music的支持

### ISSUE THREAD

**Issue by Kotlin537** [Block-Network/StatusBarLyric#155]
**环境信息**

模块版本: 
Android版本: 
屏幕类型: 

**在最新的release版本中能否复现**

**bug内容**

**复现方法**

**Comment by xiaowine** [comment]
> **环境信息**
> 
> 模块版本: Android版本: 屏幕类型:
> 
> **在最新的release版本中能否复现**
> 
> **bug内容**
> 
> **复现方法**

是否有车载歌词

**Comment by Kotlin537** [comment]
无，但有魅族状态栏歌词

**Comment by 577fkj** [comment]
已经提[issues](https://github.com/Moriafly/DsoMusic/issues/108)
