### ISSUE TITLE
模块不生效

### ISSUE THREAD

**Issue by Ricardo669** [Block-Network/StatusBarLyric#156]
环境信息

模块版本:3.22.45，4.4.3均无法使用
Android版本:11
屏幕类型:LCD

在最新的release版本中能否复现：能
bug内容：
MIUI 13，网易云8.7.01，尝试test歌词显示过一次，但后续网易云播放时不显示，test也不再显示
新版截图：
![Screenshot_2022-03-08-15-24-29-993_statusbar.lyric.jpg](https://user-images.githubusercontent.com/100527439/157187660-3549f75e-5acf-4604-b0a3-d898abee23c2.jpg)
（旧版截图：）
![Screenshot_2022-03-08-06-56-17-947_miui.statusbar.lyric.jpg](https://user-images.githubusercontent.com/100527439/157133144-6ee5fdc6-b766-4d3e-b482-741a6b48699f.jpg)
![IMG_20220308_070708.jpg](https://user-images.githubusercontent.com/100527439/157133384-15ca861f-eff0-4974-ab99-080b6af59f33.jpg)
新版也是只能显示测试歌词，hook system ui成功，但不能显示网易云歌词（无论用蓝牙歌词还是状态栏歌词，不知道是不是我操作有误）
（我应该如何抓取debug的日志并上传？希望能留下联系方式。）

**Comment by Ricardo669** [comment]
通过电报联系：https://t.me/Ricardo996

**Comment by 577fkj** [comment]
你这界面你最新?

**Comment by Ricardo669** [comment]
> 你这界面你最新?
两个版本都试过了
![Screenshot_2022-03-08-15-24-29-993_statusbar.lyric.jpg](https://user-images.githubusercontent.com/100527439/157187474-ea1f33be-e3bd-471a-9785-b3e2436e47df.jpg)
![IMG_20220308_152124.jpg](https://user-images.githubusercontent.com/100527439/157187176-3594413f-5b6e-4a2c-b751-cea1589e1ee5.jpg)
