### ISSUE TITLE
12L上不会自动隐藏时间

### ISSUE THREAD

**Issue by JonyWinner** [Block-Network/StatusBarLyric#162]
**环境信息**

模块版本: 4.4.3
Android版本: 12L
屏幕类型: 

**在最新的release版本中能否复现**

**bug内容**
在12L上不会自动隐藏时间

**复现方法**
开启总开关后如图所示
![Screenshot_20220319-205108_Pixel 启动器](https://user-images.githubusercontent.com/63949560/159121918-0b18344f-20e7-464e-bde5-29133c0b9b8e.png)

**Comment by xiaowine** [comment]
> **环境信息**
> 
> 模块版本: 4.4.3 Android版本: 12L 屏幕类型:
> 
> **在最新的release版本中能否复现**
> 
> **bug内容** 在12L上不会自动隐藏时间
> 
> **复现方法** 开启总开关后如图所示 ![Screenshot_20220319-205108_Pixel 启动器](https://user-images.githubusercontent.com/63949560/159121918-0b18344f-20e7-464e-bde5-29133c0b9b8e.png)

evo系统？

**Comment by JonyWinner** [comment]
yep

**Comment by xiaowine** [comment]
> yep

那不能新版就合理了
