### ISSUE TITLE
添加纯音乐隐藏歌词

### ISSUE THREAD

**Issue by Eric-Joker** [Block-Network/StatusBarLyric#181]
**环境信息**

模块版本: 5.2.5
Android版本: 11
屏幕类型: 全面屏

**在最新的release版本中能否复现**
不能
**建议内容**

根据歌词内容（该歌曲为纯音乐/DJ请欣赏）来判断是否为纯音乐，若是则自动隐藏歌词
**复现方法**

**Comment by 577fkj** [comment]
纯音乐也不会给歌词 我咋判断

**Comment by Eric-Joker** [comment]
> 纯音乐也不会给歌词 我咋判断

别的软件不知道，，以酷我音乐为例，酷我音乐的纯音乐会给一条歌词：该歌曲为纯音乐请欣赏

**Comment by 577fkj** [comment]
我有时间看看

**Comment by 577fkj** [comment]
已经实现 自行填写屏蔽歌词即可
