### ISSUE TITLE
colorOS 12 相关问题

### ISSUE THREAD

**Issue by ASTWY** [Block-Network/StatusBarLyric#184]
**环境信息**

模块版本: 5.25
Android版本: 12
屏幕类型: oneplus 8T

**在最新的release版本中能复现**

**bug内容**

歌词自定义位置无法覆盖时间的位置，即使开启了隐藏时间
**复现方法**

自定义中开启隐藏时间
自定义中设置歌词左右位置为-170

**Comment by 577fkj** [comment]
已知colorOS无法隐藏时间
