### ISSUE TITLE
5.2.5版本不显示状态栏歌词

### ISSUE THREAD

**Issue by Fbk-waifu** [Block-Network/StatusBarLyric#186]
**环境信息**

模块版本: 5.2.5
Android版本: 12
屏幕类型: OLED

**在最新的release版本中能否复现**
能
**bug内容**

不显示状态栏歌词，但网易云设置里提示hook成功
**复现方法**

使用5.2.5的状态栏歌词就会不显示状态栏歌词，但4.4.3版本则能够显示
[LSPosed_2022-04-14T12_28_50.037.zip](https://github.com/Block-Network/StatusBarLyric/files/8493065/LSPosed_2022-04-14T12_28_50.037.zip)

**Comment by 577fkj** [comment]
请下载最新debug版本后重新抓取日志

**Comment by Fbk-waifu** [comment]
[LSPosed_2022-04-15T19_35_59.363.zip](https://github.com/Block-Network/StatusBarLyric/files/8495695/LSPosed_2022-04-15T19_35_59.363.zip)
这是用最新的debug版本抓取的日志

**Comment by xiaowine** [comment]
> [LSPosed_2022-04-15T19_35_59.363.zip](https://github.com/Block-Network/StatusBarLyric/files/8495695/LSPosed_2022-04-15T19_35_59.363.zip) 这是用最新的debug版本抓取的日志

没有任何问题，已经获取到歌词，检查其他模块
![image](https://user-images.githubusercontent.com/68009112/163701540-cc7c50ad-78ac-444c-aec1-78c3c9dd5b35.png)

**Comment by 577fkj** [comment]
> [LSPosed_2022-04-15T19_35_59.363.zip](https://github.com/Block-Network/StatusBarLyric/files/8495695/LSPosed_2022-04-15T19_35_59.363.zip) 这是用最新的debug版本抓取的日志

我没看到hook systemui的日志 请确定勾选了systemui并且重启了 或者重新优化试试

**Comment by Fbk-waifu** [comment]
> > [LSPosed_2022-04-15T19_35_59.363.zip](https://github.com/Block-Network/StatusBarLyric/files/8495695/LSPosed_2022-04-15T19_35_59.363.zip) 这是用最新的debug版本抓取的日志
> 
> 我没看到hook systemui的日志 请确定勾选了systemui并且重启了 或者重新优化试试

昨天换了MIUI eu，问题消失了
