### ISSUE TITLE
状态栏正中间有摄像头，时间和网速没法被歌词挤到摄像头右边

### ISSUE THREAD

**Issue by 1457384613gh** [Block-Network/StatusBarLyric#192]
状态栏正中间有摄像头，时间和网速没法被歌词挤到摄像头右边。
状态栏正好被位于状态栏正中间的摄像头切成了两半。
打算合理分配空间，左边一半完全显示状态栏歌词，右边一半显示【时间】【网速】【wifi】【电池】【信号】等……
发现 歌词 可以从左侧开始把 【时间】【网速】往右推，但无法推到摄像头右边去。
有办法，把【时间】【网速】推到摄像头右边去吗？
![Screenshot_2022-05-11-18-12-47-840_cn toside music mobile](https://user-images.githubusercontent.com/69227436/167827635-70d1f020-081b-4d59-ac06-72ca3f884826.jpg)

**Comment by 577fkj** [comment]
没办法

**Comment by 1457384613gh** [comment]
啊？这种情况，都只能操作左侧状态栏的吗？那我去给官方写反馈，让他们把网速丢到右边去。正好下拉以后，网速就是在右边的。
![Screenshot_2022-05-11-18-31-44-671_cn.toside.music.mobile.jpg](https://user-images.githubusercontent.com/69227436/167830379-5437f279-5881-4337-b632-c41402169821.jpg)
![Screenshot_2022-05-11-18-32-55-792_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/69227436/167830546-f6362627-3983-4077-8c3d-5409733aff8a.jpg)
