### ISSUE TITLE
请求适配 洛雪音乐。

### ISSUE THREAD

**Issue by 1457384613gh** [Block-Network/StatusBarLyric#194]
请求给 洛雪音乐 适配状态栏歌词。
这个 app 可以免费播放五大平台的会员歌曲和无损音乐，用户也很多。
这个是开源的 app，虽然没有车载蓝牙歌词功能，但应该能够根据源代码，为这个 app 设计一个专享接口吧？开源的本机的桌面悬浮歌词可以作为接口吗？
该 app 的源代码如下链接。
https://github.com/lyswhut/lx-music-mobile

**Comment by qqlittleice233** [comment]
@1457384613gh 已适配洛雪音乐主分支 4e30987
