### ISSUE TITLE
PixelUI Android13版本无法使用

### ISSUE THREAD

**Issue by 2420195176** [Block-Network/StatusBarLyric#195]
**环境信息**

模块版本: 5.2.5(157)-release
Android版本: 13 beta2
屏幕类型: 中置挖孔屏

**在最新的release版本中能否复现**
能

**bug内容**

无法使用 重启SystemUI后也没有Hook系统界面成功的通知

**复现方法**

启用模块，之后重启系统界面，没有弹出Hook系统界面成功的通知，进入网易云开启设置里状态栏歌词后仍然无法使用（状态栏无变化）

**[SystemUIGoogle.zip](https://github.com/Block-Network/StatusBarLyric/files/8743183/SystemUIGoogle.zip)**
[LSPosed_2022-05-21T01_52_37.146991.zip](https://github.com/Block-Network/StatusBarLyric/files/8743195/LSPosed_2022-05-21T01_52_37.146991.zip)

**Comment by 577fkj** [comment]
试试最新ci版本
