### ISSUE TITLE
请求适配VIVO i音乐

### ISSUE THREAD

**Issue by qiu1011** [Block-Network/StatusBarLyric#200]
请求状态栏歌词适配VIVO OrignOS系统自带i音乐软件

**Comment by xiaowine** [comment]
> 请求状态栏歌词适配VIVO OrignOS系统自带i音乐软件

请发一个apk

**Comment by qiu1011** [comment]
> > 请求状态栏歌词适配VIVO OrignOS系统自带i音乐软件
> 
> 请发一个apk

https://tsog.lanzouf.com/iiebA06bdeuf

**Comment by xiaowine** [comment]
MIUI系统不能使用此软件
