### ISSUE TITLE
模块自动隐藏问题优化

### ISSUE THREAD

**Issue by yydstome** [Block-Network/StatusBarLyric#202]
**环境信息**

模块版本: 
Android版本: 
屏幕类型: 

**在最新的release版本中能否复现**

**bug内容**

**复现方法**

模块开启自动隐藏通知和实时网速后，每次界面刷新，通知和网速就会显示出来。
有时候用户可能为了保险起见会先开启自动隐藏功能，但有时候在系统设置里设置为不显示通知或者网速后，每次界面刷新，就会重新跳出来。
希望优化一下逻辑。如果用户没有开启通知图标和网速，即使模块内已经开启了自动隐藏，希望可以不要自动显示出来。

**Comment by 577fkj** [comment]
> **环境信息**
> 
> 模块版本: Android版本: 屏幕类型:
> 
> **在最新的release版本中能否复现**
> 
> **bug内容**
> 
> **复现方法**
> 
> 模块开启自动隐藏通知和实时网速后，每次界面刷新，通知和网速就会显示出来。 有时候用户可能为了保险起见会先开启自动隐藏功能，但有时候在系统设置里设置为不显示通知或者网速后，每次界面刷新，就会重新跳出来。 希望优化一下逻辑。如果用户没有开启通知图标和网速，即使模块内已经开启了自动隐藏，希望可以不要自动显示出来。

我并不能知道开关是模块开启的还是用户手动开启的
这优化可能会导致更多bug出现
