### ISSUE TITLE
歌词左右 上下位置无法控制

### ISSUE THREAD

**Issue by MartinVon1021** [Block-Network/StatusBarLyric#209]
MIUI13 小米12 5.3.1
歌词上下位置实际上控制的是左右
歌词左右位置不生效

**Comment by xiaowine** [comment]
> MIUI13 小米12 5.3.1 歌词上下位置实际上控制的是左右 歌词左右位置不生效

请标明版本，和模块编译时间

**Comment by MartinVon1021** [comment]
米12 MIUI13 13.0.36.0
模块 5.3.1(161) 6-24 18:41:24
