### ISSUE TITLE
请求适配 Spotify 与 Apple Music

### ISSUE THREAD

**Issue by KarlLee830** [Block-Network/StatusBarLyric#211]
Spotify 与 Apple Music 作为国内较多人使用的海外音乐流媒体软件，拥有较多的用户群。
请求作者适配这两款软件。

**Comment by qi-mooo** [comment]
@KarlLee830 Spotify大部分并没有歌词吧，Apple Music真的有很多人在Android上用吗？

**Comment by 577fkj** [comment]
Spotify 自己的歌词都不完美

**Comment by KarlLee830** [comment]
> @KarlLee830 Spotify大部分并没有歌词吧，Apple Music真的有很多人在Android上用吗？

Spotify现在已经更新歌词功能，大部分歌曲都已经有歌词了。

**Comment by KarlLee830** [comment]
> Spotify 自己的歌词都不完美

时间轴歌词功能已经更新支持了。

![Screenshot_2022-07-04-14-37-38-788_com spotify music](https://user-images.githubusercontent.com/61072264/177095922-165754c0-f0a8-48b5-9e15-32c3b3168ddc.jpg)

**Comment by 577fkj** [comment]
> > Spotify 自己的歌词都不完美
> 
> 时间轴歌词功能已经更新支持了。
> 
> ![Screenshot_2022-07-04-14-37-38-788_com spotify music](https://user-images.githubusercontent.com/61072264/177095922-165754c0-f0a8-48b5-9e15-32c3b3168ddc.jpg)

其实还有一个原因就是，歌词很难获取，要分析的话混淆太恶心了

**Comment by KarlLee830** [comment]
> > > Spotify 自己的歌词都不完美
> > 
> > 
> > 时间轴歌词功能已经更新支持了。
> > ![Screenshot_2022-07-04-14-37-38-788_com spotify music](https://user-images.githubusercontent.com/61072264/177095922-165754c0-f0a8-48b5-9e15-32c3b3168ddc.jpg)
> 
> 其实还有一个原因就是，歌词很难获取，要分析的话混淆太恶心了

其实可以通过安卓接口来获取歌词名与歌手与播放进度信息，通过第三方接口如QQ音乐或网易云音乐来获取歌词进行显示。

**Comment by 577fkj** [comment]
> > > > Spotify 自己的歌词都不完美
> > > 
> > > 
> > > 时间轴歌词功能已经更新支持了。
> > > ![Screenshot_2022-07-04-14-37-38-788_com spotify music](https://user-images.githubusercontent.com/61072264/177095922-165754c0-f0a8-48b5-9e15-32c3b3168ddc.jpg)
> > 
> > 
> > 其实还有一个原因就是，歌词很难获取，要分析的话混淆太恶心了
> 
> 其实可以通过安卓接口来获取歌词名与歌手与播放进度信息，通过第三方接口如QQ音乐或网易云音乐来获取歌词进行显示。

好想法，要不起名叫 状态栏歌词扩展 吧
项目就叫 https://github.com/Block-Network/StatusBarLyricExt

**Comment by KarlLee830** [comment]
> > > > > Spotify 自己的歌词都不完美
> > > > 
> > > > 
> > > > 时间轴歌词功能已经更新支持了。
> > > > ![Screenshot_2022-07-04-14-37-38-788_com spotify music](https://user-images.githubusercontent.com/61072264/177095922-165754c0-f0a8-48b5-9e15-32c3b3168ddc.jpg)
> > > 
> > > 
> > > 其实还有一个原因就是，歌词很难获取，要分析的话混淆太恶心了
> > 
> > 
> > 其实可以通过安卓接口来获取歌词名与歌手与播放进度信息，通过第三方接口如QQ音乐或网易云音乐来获取歌词进行显示。
> 
> 好想法，要不起名叫 状态栏歌词扩展 吧 项目就叫 https://github.com/Block-Network/StatusBarLyricExt

抱歉之前没有看到您的这个repo😂，期待您这个项目开发完成的一天。
