### ISSUE TITLE
三星s20u 适配

### ISSUE THREAD

**Issue by kaliCYH** [Block-Network/StatusBarLyric#217]
**环境信息**

模块版本: 5.3.2
Android版本: 安卓12 oneui4.1
屏幕类型: Dynamic AMOLED

**在最新的release版本中能否复现**
yes
**bug内容**
hook成功但无法显示
**复现方法**
使用不了
lsposed日志
https://t.me/StatusBarLyric_Chat/80782

system ui
https://t.me/StatusBarLyric_Chat/80785

**Comment by 577fkj** [comment]
@kaliCYH [回复 GitHub]
音乐软件要不没开蓝牙歌词 要不没开状态栏歌词

**Comment by kaliCYH** [comment]
@577fkj https://t.me/StatusBarLyric_Chat/80893

**Comment by kaliCYH** [comment]
4.4.3版可以正常hook但是5.0开始就不行
