### ISSUE TITLE
模块作用域，LX Music 没有成为【推荐应用】

### ISSUE THREAD

**Issue by 1457384613gh** [Block-Network/StatusBarLyric#226]
希望LX Music可以成为模块作用域里的【推荐应用】，被自动勾选，免得手动勾选。

![IMG_20220925_204008.jpg](https://user-images.githubusercontent.com/69227436/192143937-f233a361-79d2-4bbd-a36c-b6fd9dfdef65.jpg)

**Comment by xiaowine** [comment]
> 希望LX Music可以成为模块作用域里的【推荐应用】，被自动勾选，免得手动勾选。
> 
> ![IMG_20220925_204008.jpg](https://user-images.githubusercontent.com/69227436/192143937-f233a361-79d2-4bbd-a36c-b6fd9dfdef65.jpg)

测试版已添加
