### ISSUE TITLE
防烧屏开启时，歌词左右位置调节存在问题

### ISSUE THREAD

**Issue by ShanshanHY** [Block-Network/StatusBarLyric#230]
**环境信息**

模块版本: 5.4.0
Android版本: 13
屏幕类型: OLED

**在最新的release版本中能否复现**
完全复现

**bug内容**

`歌词左右位置调节` 在退出 `[墨 状态栏歌词]` 后一段时间失效，再次启动`[墨 状态栏歌词]`-`[自定义]`页面后自动恢复

**复现方法**

同bug内容

**Comment by ShanshanHY** [comment]
> **环境信息**
> 
> 模块版本: 5.4.0 Android版本: 13 屏幕类型: OLED
> 
> **在最新的release版本中能否复现** 完全复现
> 
> **bug内容**
> 
> `歌词左右位置调节` 在退出 `[墨 状态栏歌词]` 后一段时间失效，再次启动`[墨 状态栏歌词]`-`[自定义]`页面后自动恢复
> 
> **复现方法**
> 
> 同bug内容
**更正，开启防烧屏时出现以上bug**

**Comment by Extrwave** [comment]
这就是防烧屏的正常功能，移动位置

**Comment by ShanshanHY** [comment]
> 这就是防烧屏的正常功能，移动位置


防烧屏，指的是在触发的一瞬间导致左右位置调节失效，大幅度移动 几十dp，然后再也不动么？建议你使用最新releases亲自测试后评论
你可以在[酷安] (https://www.coolapk.com/apk/statusbar.lyric)下找到同样拥有此bug的人，他们的共同点是左右位置调节一段时间后时效
我已经修好了这个bug并且合并进了dev仓库 ，并主动关闭了issue，请不要继续讨论这个问题
