### ISSUE TITLE
【问题反馈】Android13上系统反色无效，请求修复

### ISSUE THREAD

**Issue by sunburst96** [Block-Network/StatusBarLyric#235]
**环境信息**

模块版本: 5.4.0
Android版本: 13
屏幕类型: 水滴屏

**在最新的release版本中能否复现**

**bug内容**

**复现方法**

[LSPosed_2022-10-09T15_16_27.006315.zip](https://github.com/Block-Network/StatusBarLyric/files/9740965/LSPosed_2022-10-09T15_16_27.006315.zip)

**Comment by xiaowine** [comment]
@SunflowerThom 有问题就关闭系统反色
