### ISSUE TITLE
[bug反馈]横屏后，再竖屏状态栏歌词不可见。小米9，miui12.0.6

### ISSUE THREAD

**Issue by Duoluozhijkhshang** [Block-Network/StatusBarLyric#238]
**环境信息**

模块版本: 5.4.0
Android版本: android 10  ,miui12.0.6
屏幕类型: 

**在最新的release版本中能否复现**
能
**bug内容**

每次横屏，恢复竖屏后状态栏歌词不再显示，再次横屏能还能看到状态栏歌词，但竖屏不能了
**复现方法**

以任何方式横屏后，再次竖屏就看不到状态栏歌词了

**Comment by qqlittleice233** [comment]
@Duoluozhijkhshang 无法复现

**Comment by Duoluozhijkhshang** [comment]
横屏后竖屏，就会卡在横屏前那句歌词，然后横屏就会正常显示

**Comment by Duoluozhijkhshang** [comment]
而且这个状态栏歌词里的重启SystemUI，没有效果，隔壁息屏歌词里的就能正常重启
