### ISSUE TITLE
请求增加歌词图标左侧边距设置

### ISSUE THREAD

**Issue by MUKAPP** [Block-Network/StatusBarLyric#239]
**环境信息**

模块版本: 5.4.0
Android版本: 12
屏幕类型:水滴屏

**在最新的release版本中能否复现**

**bug内容**

一个小建议，如题
添加背景之后图标紧贴着左边不太好看
希望可以增加歌词图标左侧边距的设置
![Screenshot_20221020-233616_Via](https://user-images.githubusercontent.com/41848070/196994681-5d76867b-b1f1-4d6d-81a0-4c9bb572e2e3.png)

**复现方法**

**Comment by MUKAPP** [comment]
还有歌词上下边距如果可以设置的话就更好了（

**Comment by xiaowine** [comment]
@MUKAPP 你说的不都有吗？

**Comment by MUKAPP** [comment]
> @MUKAPP 你说的不都有吗？

有吗，抱歉我没找到（（
我做了张图，里面有我的预期效果，你看看
![IMG_20221020_235948](https://user-images.githubusercontent.com/41848070/196999685-887785c4-3de0-4137-85b9-94596163e784.png)

**Comment by MUKAPP** [comment]
还有就是开启歌词边缘虚化之后，歌词滚动到结尾，结尾还是虚化的，或许往歌词结尾添加一个空格会不会好一点
