### ISSUE TITLE
在MIUI安卓13系统下，状态栏歌词失效

### ISSUE THREAD

**Issue by xhanhh** [Block-Network/StatusBarLyric#240]
**环境信息**

模块版本: StatusBarLyric-5.4.0(163)-release-1664674584386-signed
Android版本: CUPID-MIUI13.1.22.10.19-Android13
屏幕类型: 1080x2400-419dpi
qq音乐：11.10.1.8

**在最新的release版本中能否复现**
是

**bug内容**

qq音乐设置选项中无状态栏歌词选项，模块开关正常，状态栏歌词也无法生效。

**复现方法**

重启全部作用域，打开qq音乐，仍无“魅族状态栏歌词”选项，多次重启无果。

**Comment by Anesthesia271** [comment]
遇到了类似的问题，我的设备是 MI 11，MIUI版本是v14.0.22.12.8.DEV，在我的设备上，小米自带的音乐能正常显示歌词，但是网易云音乐始终无法显示，qq音乐未进行测试，查看日志也没有抛出任何错误
