### ISSUE TITLE
Lx-Music开启模块后，无法编辑歌曲列表，无法删除列表中的歌曲；还有，局域网同步功能失效。

### ISSUE THREAD

**Issue by 1457384613gh** [Block-Network/StatusBarLyric#242]
Lx-Music开启模块后，
- 无法编辑歌曲列表，无法删除列表中的歌曲。
- 局域网同步功能失效。

**Comment by qqlittleice233** [comment]
Dev早已修复
https://github.com/Block-Network/StatusBarLyric/commit/79136aa199334142471b9fac1bf72908f05f564d

**Comment by 1457384613gh** [comment]
新的 release，什么时候出来啊？

**Comment by 1457384613gh** [comment]
> @1457384613gh 天和地利人和时

已经到月底了。
应该可以release个新版本了吧？
