### ISSUE TITLE
真我ColorOS，状态栏歌词会左右偏移

### ISSUE THREAD

**Issue by Master-Panda** [Block-Network/StatusBarLyric#247]
**环境信息**

模块版本: 5.4.0
Android版本: 13
屏幕类型: AMOLED

**在最新的release版本中能否复现**能

**bug内容**

**复现方法**

**Comment by Master-Panda** [comment]
**环境信息**

模块版本: 5.4.0
Android版本: 13
屏幕类型: AMOLED

**在最新的release版本中能否复现**能

**bug内容**


**复现方法**

**Comment by xiaowine** [comment]
@Master-Panda 测试版已经修复

**Comment by Master-Panda** [comment]
我用的是最新的ci版本，刚刚又出现了这个问题，这次的偏移是比较小的，之前的偏移是挺大的












HUIMIN
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月14日(周一) 晚上11:35
收件人: ***@***.***&gt;;
抄送: "Master ***@***.******@***.***&gt;;
主题: Re: [Block-Network/StatusBarLyric] 真我ColorOS，状态栏歌词会左右偏移 (Issue #247)




 
@Master-Panda 测试版已经修复

**Comment by Master-Panda** [comment]
往往出现这种问题的时候，歌词的最大限度也失效了，比如图片这种情况，原来是不会占满整个状态栏的，但是现在却占满了












HUIMIN
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月14日(周一) 晚上11:35
收件人: ***@***.***&gt;;
抄送: "Master ***@***.******@***.***&gt;;
主题: Re: [Block-Network/StatusBarLyric] 真我ColorOS，状态栏歌词会左右偏移 (Issue #247)




 
@Master-Panda 测试版已经修复
