### ISSUE TITLE
功能建议（不是bug）

### ISSUE THREAD

**Issue by syc0000000** [Block-Network/StatusBarLyric#252]
希望大佬能适配一下MIX4哈哈就屏下那一坨能不能用来显示歌词，现在最大宽度调不过去，调到中间摄像头位置后再加就没用了

**Comment by syc0000000** [comment]
就像这样
![QQ截图20221228140320](https://user-images.githubusercontent.com/112924913/209765760-ebae506d-c2cf-4943-9867-8c0443885741.png)

**Comment by 577fkj** [comment]
没设备

**Comment by syc0000000** [comment]
刷了个模块OK了，叫 MIX4 全屏幕显示
