### ISSUE TITLE
请教一下隐藏通知图标是怎么实现的？我关闭隐藏通知图标之后，通知图标依然没有显示，能否手动修改文件，恢复正常？

### ISSUE THREAD

**Issue by YEW151** [Block-Network/StatusBarLyric#255]
**环境信息**

模块版本: 5.4
Android版本: 11
屏幕类型: lcd 1080p

**在最新的release版本中能否复现**

**bug内容**

关闭隐藏通知图标以及卸载模块之后，通知图标依然没有显示
**复现方法**

能否手动修改文件，恢复通知图标？系统为MIUI

**Comment by xiaowine** [comment]
https://github.com/Block-Network/StatusBarLyric/blob/main/app/src/main/java/statusbar/lyric/utils/Utils.kt#L127
