### ISSUE TITLE
[Bug] MIUI 12 安卓10 旋转屏幕后竖屏歌词不再更新，切换横屏歌词正常更新

### ISSUE THREAD

**Issue by xireiki** [Block-Network/StatusBarLyric#267]
**环境信息**

模块版本: 5.4.2
Android版本: 10
屏幕类型: lcd

**在最新的release版本中能否复现**

**bug内容**

手机📱：Mi 8 Lite

手机竖屏状态下播放歌曲，状态栏歌词正常显示，关闭方向锁定，旋转屏幕为横屏，歌词正常显示，再切换回竖屏，歌词卡在旋转屏幕为横屏之前最后更新的歌词。

此时打开“墨·状态栏歌词”提示：“HOOK 系统界面成功”

**复现方法**

1.关闭“方向锁定”

2.播放音乐（实测所有音乐软件均可，这里是椒盐音乐）以显示状态栏歌词

3.打开“墨·状态栏歌词”

4.旋转手机至横屏方向，此时系统旋转屏幕

5.查看状态栏歌词，发现正常更新

6.旋转手机至竖屏，此时查看状态栏歌词发现歌词一直显示旋转屏幕至横屏前最后一句，等待半小时，未恢复，最后手动重启系统ui（sudo pkill systemui）初始化。

7.日志：log/modules_2023-01-19T10:45:20.021.log

8.日志链接：https://xireiki.lanzoub.com/ieiIX0ld39gd

9.系统UI链接：https://xireiki.lanzoub.com/i5vZ10ld3oda

**Comment by xiaowine** [comment]
#238
