### ISSUE TITLE
［Bug］打开其他APP时音乐中断

### ISSUE THREAD

**Issue by EscapeA** [Block-Network/StatusBarLyric#268]
**环境信息**

模块版本: 5.4.2 
Android版本: 13
屏幕类型: 中间挖孔,OLED

**在最新的release版本中能否复现**

最新的ci版debug中可以复现,release未知

**bug内容**

小米音乐,启用模块后,播放音乐时,冷启动其他APP会导致音乐关闭

**复现方法**

0.启用模块,勾选作用域:（小米）音乐,系统界面
1.重启系统界面
2.播放音乐,状态栏歌词显示正常
3.从桌面打开其他APP（如:应用商店,Chrome）,音乐中断,通知栏媒体播放器消失

**Comment by xiaowine** [comment]
@EscapeA 我觉得是你系统问题

**Comment by EscapeA** [comment]
经过多次启用/禁用模块测试后,非此模块引起
