### ISSUE TITLE
自动隐藏通知图标失效

### ISSUE THREAD

**Issue by ZTG0421** [Block-Network/StatusBarLyric#272]
![Screenshot_2023-02-01-07-46-59-29_f23e7e35f6987d1fc0492920c7cebf60](https://user-images.githubusercontent.com/79940512/215909727-a5949c86-c3d4-42bd-a14c-68cc9920436e.jpg)

Oneplus Ace Pro 
ColorOS13

**Comment by ZTG0421** [comment]
1

**Comment by xiaowine** [comment]
@ZTG0421 只支持部分类原生和miui
