### ISSUE TITLE
适配apm4.1

### ISSUE THREAD

**Issue by xiaowine** [Block-Network/StatusBarLyric#275]
**环境信息**

模块版本: 
Android版本: 
屏幕类型: 

**在最新的release版本中能否复现**

**bug内容**

**复现方法**

https://github.com/F-19-F/amLyric/releases/tag/4.1.0
个人觉得，以前的版本就不用管了

**Comment by sunburst96** [comment]
是的，苹果音乐不会有人想着用旧版，完全没必要

**Comment by Arlene947** [comment]
今天4.1.1了 大鸽子 速速把f19佬的代码抄过来
