### ISSUE TITLE
程序异常中止后状态栏歌词不消失

### ISSUE THREAD

**Issue by Muzyli** [Block-Network/StatusBarLyric#279]
**环境信息**

模块版本: 5.4.2
Android版本: 12
屏幕类型: oled

**在最新的release版本中能否复现**
能
**bug内容**

程序使用api调用状态栏歌词后，其异常中止会导致状态栏歌词持续显示不消失
**复现方法**

使用洛雪音乐，播放音乐出现状态栏歌词后，后台强行关闭洛雪音乐，状态栏歌词不消失，直到下一次打开洛雪音乐或播放其它可以调用状态栏歌词的音乐

**个人建议**
建议新增一个单条歌词最大显示时间，避免歌词在异常情况下持续占用状态栏

**Comment by xiaowine** [comment]
@Muzyli 有没有可能已经有了

**Comment by Muzyli** [comment]
是在下瞎了
