### ISSUE TITLE
Cherish OS状态栏歌词开启不成功

### ISSUE THREAD

**Issue by fengyiZs** [Block-Network/StatusBarLyric#281]
**环境信息**

模块版本: 5.4.2
Android版本: 13
屏幕类型: 
AMOLED
**在最新的release版本中能否复现**
可以
**bug内容**
在正确开启状态栏歌词后状态栏歌词无法显示

**复现方法**
同上，在音乐软件里有“状态栏歌词”的选项，但开启无作用，刷新hook也无效

**Comment by xiaowine** [comment]
@fengyiZs 日志

**Comment by qqlittleice233** [comment]
没有后续回复，关闭issue
