### ISSUE TITLE
请求适配Apple Music 4.1.0

### ISSUE THREAD

**Issue by Chuanx-x** [Block-Network/StatusBarLyric#284]
**环境信息**

模块版本: 5.4.2
Android版本: 10
屏幕类型: LCD

**在最新的release版本中能否复现**
非bug
**bug内容**

非bug
**复现方法**

非bug
催更催更催更，这就是个催更issue（

**Comment by xiaowine** [comment]
#275

**Comment by Chuanx-x** [comment]
这个模块没说明不晓得怎么用… 两个模块同时选中Apple Music为作用域时Apple Music会闪退，任意取消一个勾选就恢复正常，但是也没歌词显示（
