### ISSUE TITLE
关于最新版酷我音乐10.3.8.1无法显示状态栏歌词问题的解决方案

### ISSUE THREAD

**Issue by dzghxs** [Block-Network/StatusBarLyric#290]
**环境信息**

模块版本: 5.4.2
Android版本: 12
屏幕类型: 

**在最新的release版本中能否复现**
修改Kuwo.kt文件中的 "cn.kuwo.mod.playcontrol.RemoteControlLyricMgr".hookAfterMethod("updateLyricText", String::class.java)改为"cn.kuwo.mod.playcontrol.n".hookAfterMethod("a", String::class.java)，编译运行

**Comment by dzghxs** [comment]
下载源码修改

**Comment by MeetDead** [comment]
> 

改好之后，那个Kuwo.kt文件怎么使用呢

**Comment by dzghxs** [comment]
使用Android studio运行该项目，修改Kuwo.kt的代码，修改后，编译运行

**Comment by MeetDead** [comment]
> 使用Android studio运行该项目，修改Kuwo.kt的代码，修改后，编译运行

我不太会，大佬能发一下你的包吗

**Comment by dzghxs** [comment]
[StatusBarLyric-5.4.2(165)-release-1681867351821.apk.zip](https://github.com/Block-Network/StatusBarLyric/files/11267673/StatusBarLyric-5.4.2.165.-release-1681867351821.apk.zip)
解压，安装试试，用了自己的签名，需要卸载之前的，再安装这个

**Comment by MeetDead** [comment]
> [StatusBarLyric-5.4.2(165)-release-1681867351821.apk.zip](https://github.com/Block-Network/StatusBarLyric/files/11267673/StatusBarLyric-5.4.2.165.-release-1681867351821.apk.zip) 解压，安装试试，用了自己的签名，需要卸载之前的，再安装这个

可以用了，感谢大佬！

**Comment by xiaowine** [comment]
坏消息，RemoteControlLyricMgr整个类都没了

**Comment by dzghxs** [comment]
> 坏消息，RemoteControlLyricMgr整个类都没了

新版开混淆了，所以找着费劲了，最新的是，"cn.kuwo.mod.playcontrol.m".hookAfterMethod("a", String::class.java)

**Comment by xiaowine** [comment]
> > 坏消息，RemoteControlLyricMgr整个类都没了
> 
> 新版开混淆了，所以找着费劲了，最新的是，"cn.kuwo.mod.playcontrol.m".hookAfterMethod("a", String::class.java)

这样的话只有上dexkit了
