### ISSUE TITLE
Pixel Experience系统内歌词与锁屏界面运营商冲突

### ISSUE THREAD

**Issue by Glow1134** [Block-Network/StatusBarLyric#291]
**环境信息**

模块版本: 5.4.2（165）-release
Android版本: 13
屏幕类型: 左侧挖孔

**在最新的release版本中能否复现**

**bug内容**
<打开锁屏自动隐藏运营商选项后运营商字样仍未消失>

**复现方法**
<播放音乐然后锁屏>

**Comment by xiaowine** [comment]
@Glow1134 此功能仅支持miui
