### ISSUE TITLE
请求适配oto music

### ISSUE THREAD

**Issue by CGBB0** [Block-Network/StatusBarLyric#293]
https://wwac.lanzouf.com/ilDiD0t1flkh
密码:doo![IMG_20230415_222157.jpg](https://user-images.githubusercontent.com/101496448/232230399-b39fb6ad-6359-4380-9038-1f9cb7a9a6bc.jpg)

在左下角打开歌词界面

**Comment by SteveZMTstudios** [comment]
请求适配
![Uploading Screenshot_2023-05-20-14-33-26-491_com.piyush.musie.jpg…]()
