### ISSUE TITLE
歌词原文与译文之间出现NO GLYPH字符

### ISSUE THREAD

**Issue by RuriAlpha** [Block-Network/StatusBarLyric#295]
**环境信息**

模块版本: 5.4.2(165)-release
Android版本: 13
屏幕类型: 中置挖孔

**在最新的release版本中能否复现**
能
**bug内容**

歌词原文与译文之间出现NO GLYPH字符
![Screenshot_2023-04-21-16-02-07-583_com miui home](https://user-images.githubusercontent.com/40235755/233580623-c02905f9-9ecc-48a8-8b80-d56b6d8289f5.jpg)

**复现方法**

使用椒盐音乐播放一首有译文的外文歌

**Comment by xiaowine** [comment]
@RuriAlpha 非模块问题
