### ISSUE TITLE
透過hook原生/類原生AOD上顯示的歌名來達到歌詞顯示的效果可行嗎？

### ISSUE THREAD

**Issue by alexchiu100014** [Block-Network/StatusBarLyric#301]
**环境信息**

模块版本: 5.4.2
Android版本: 13 qpr3?
屏幕类型: 2400x1080

**在最新的release版本中能否复现**

**bug内容**
如題
![image](https://user-images.githubusercontent.com/48598830/236671350-1f0f7eea-9a09-406f-b276-399985db4d8b.png)

**复现方法**

**Comment by xiaowine** [comment]
理论可行
