### ISSUE TITLE
网易云8.9.50版本无法正常显示歌词

### ISSUE THREAD

**Issue by Kgym-Hina** [Block-Network/StatusBarLyric#302]
**环境信息**

模块版本: 5.4.2/最新CI版本均出现
Android版本: 13
屏幕类型: OLED

**在最新的release版本中能否复现**

能

**bug内容**

重启网易云8.9.50和系统UI后，确保在网易云设置内开启了状态栏歌词选项，播放乐曲，无论点不点设置内的刷新均不显示

[Log地址](https://airportal.cn/186562/4QeTPzxDX1) 

**复现方法**

1. 下载最新release版本
2. 重启SystemUI
3. 杀掉网易云，重新打开
4. 打开网易云设置，打开开关，点击刷新
5. 播放音乐
6. 发现无效，再次重启网易云后播放音乐
7. 尝试更换CI版本
8. 如上（重复）

**Comment by qqlittleice233** [comment]
![image](https://github.com/Block-Network/StatusBarLyric/assets/60041789/34c8c98c-5749-4b7b-ae0f-1a7669b7e01c)

**Comment by Kgym-Hina** [comment]
抱歉，文件因为过了有效期，自动销毁了，我马上重传：https://www.123pan.com/s/VZ3tVv-r4ul3.html
