### ISSUE TITLE
歌词图标格式是否考虑更换为svg

### ISSUE THREAD

**Issue by Yos-X** [Block-Network/StatusBarLyric#303]
**环境信息**

模块版本: 5.4.2
Android版本: 13
屏幕类型: 2400*1080

**在最新的release版本中能否复现**
可以

**bug内容**
base64的方式设定图标，再进行着色时，如果是半透明的颜色，则呈现出来的颜色会是 base64图标色+着色

**复现方法**

图标着半透明色

**Comment by xiaowine** [comment]
@Yos-X 模块不适合适用svg

**Comment by Yos-X** [comment]
简单的svg文件直接复制文本不可以吗
