### ISSUE TITLE
网易云无法正常显示歌词

### ISSUE THREAD

**Issue by Kgym-Hina** [Block-Network/StatusBarLyric#304]
**环境信息**

模块版本: 5.4.2/最新CI版本均出现
Android版本: 13
屏幕类型: OLED

**在最新的release版本中能否复现**

能

**bug内容**

重启网易云8.9.50和系统UI后，确保在网易云设置内开启了状态栏歌词选项，播放乐曲，无论点不点设置内的刷新均不显示

[Log地址](https://www.123pan.com/s/VZ3tVv-r4ul3.html) 

**复现方法**

1. 下载最新release版本
2. 重启SystemUI
3. 杀掉网易云，重新打开
4. 打开网易云设置，打开开关，点击刷新
5. 播放音乐
6. 发现无效，再次重启网易云后播放音乐
7. 尝试更换CI版本
8. 如上（重复）

**Comment by xiaowine** [comment]
@Kgym-Hina 重新优化呢？

**Comment by Kgym-Hina** [comment]
试了一下，laposed提示优化失败，返回值为空
重新安装后也是这样

**Comment by Kgym-Hina** [comment]
> @Kgym-Hina 重新优化呢？

![Screenshot_20230516-073252.png](https://github.com/Block-Network/StatusBarLyric/assets/22652631/c4456796-07d0-4c79-81dc-beb2200f21ff)

![Screenshot_20230516-073241.png](https://github.com/Block-Network/StatusBarLyric/assets/22652631/cfef7367-f430-437a-958d-6d17a905b893)

都失败了

**Comment by xiaowine** [comment]
@Kgym-Hina 那么你更加需要检查你的lsp了

**Comment by Kgym-Hina** [comment]
尝试将网易云版本降到8.8.70后可以正常使用
