### ISSUE TITLE
重构版，使用方法简单介绍

### ISSUE THREAD

**Issue by xiaowine** [Block-Network/StatusBarLyric#310]
![1](https://github.com/Block-Network/StatusBarLyric/assets/68009112/c3c3dd41-d4ad-4913-bb25-0c25b5a6340c)
![2](https://github.com/Block-Network/StatusBarLyric/assets/68009112/5f53dcfb-08eb-4967-a506-e3e60822fdfb)

**Comment by TutuPai** [comment]
![Uploading Screenshot_2023-06-23-10-59-38-01_b783bf344239542886fee7b48fa4b892.jpg…]()
谢谢大大😁

**Comment by Ximi-Gao** [comment]
感谢分享。希望模块越来越完美

**Comment by RFdada** [comment]
第四步没反应，没出现OK，系统是realme UI 4.0（color OS 13）

**Comment by Ximi-Gao** [comment]
重启一下system ui试试





来自阿里邮箱Android客户端------------------------------------------------------------------
***@***.***>
日　期：2023年07月05日 17:59:55
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [Block-Network/StatusBarLyric] 重构版，使用方法简单介绍 (Issue #310)

第四步没反应，没出现OK，系统是realme UI 4.0（color OS 13）

**Comment by lizhuoju** [comment]
记下可
