### ISSUE TITLE
状态栏NEED_NOT_UPDATE_TITLE

### ISSUE THREAD

**Issue by youximi** [Block-Network/StatusBarLyric#311]
**环境信息**

模块版本: 5.4.2
Android版本: 13
屏幕类型: 全面屏

**在最新的release版本中能否复现**

**bug内容**

状态栏突然边成 NEED_NOT_UPDATE_TITLE
![Uploading Screenshot_2023-07-01-21-12-16-402_com.miui.home.jpg…]()

**复现方法**

使用手机状态栏经常突然变成这样

**Comment by xiaowine** [comment]
@youximi 音乐软件问题

**Comment by youximi** [comment]
非常感谢作者在百忙之中回答我的问题 
我在lsp上只勾选了（系统界面）（小米音乐）这两款app并且平时使用在没有打开这款（小米音乐）app时 他时不时在状态栏弹出NEED_NOT_UPDATE_TITLE很影响体验 有时候看时间都看不了 目前已知唯一解决方法就是重启”sysremUI“ 但是过一会又NEED_NOT_UPDATE_TITLE

**Comment by youximi** [comment]
平时没打开音乐软件     状态栏也会突然变成NEED_NOT_UPDATE_TITLE  就算重启了“sysremUI”   但是过一会又NEED_NOT_UPDATE_TITLE

**Comment by youximi** [comment]
![Uploading Screenshot_2023-07-01-21-39-40-944_statusbar.lyric.jpg…]()

**Comment by youximi** [comment]
https://github.com/youximi/cheshi/blob/74e24cd42aa854ff11985bf757fc8e2a76846561/get_thumbnail.jpg
这个是出现问题的截图

**Comment by xiaowine** [comment]
@youximi 你可以选择屏蔽歌词，在高级设置
