### ISSUE TITLE
简单介绍使用方法

### ISSUE THREAD

**Issue by xiaowine** [Block-Network/StatusBarLyric#319]
经过一段时间的重写，《墨-状态栏歌词》已经全部重构，现在的版本相比以前的版本，更加的省电，性能占用更加的少，系统通用性更高，几乎适配所有系统。并且将获取歌词部分单独拎出来，作为单独的模块，以后可以单独更新，两者互不影响。
现在我来简单介绍新版使用方法。首先打开LSPOSED框架，激活《墨-状态栏歌词》与《Lyric Getter》这两个模块，作用域默认推荐应用即可。
之后我们打开《墨-状态栏歌词》进行配置。首先打开主开关，切记一定要打开，否则后面的所有功能将无法生效。之后再打开Hook页，打开测试模式选项，重启SystemUI，重启后点击获取Hook点，不出意外将出现一个列表。这就是模块粗略筛选后得出的结果，选择一个Hook点中作为使用的Hook点。（当状态栏出现模块名字并且时间消失则为可用的Hook点）选择后关闭测试模式，再次重启SystemUI。
到此《墨-状态栏歌词》的基础配置完成，在音乐软件内打开对应功能即可在状态栏显示歌词，要开启哪些功能可以参考[此网页](https://github.com/xiaowine/Lyric-Getter)

**Comment by UncommonRuler** [comment]
获取hook点这一步，广播接收超时

**Comment by zhinitm** [comment]
获取hook点，广播接收超时,似乎无法重启systemui
设备redmik50pro,miui14.0.11

**Comment by xiaowine** [comment]
> 获取hook点这一步，广播接收超时

打开主开关

**Comment by xiaowine** [comment]
> 获取hook点这一步，广播接收超时

打开主开关

**Comment by zhinitm** [comment]
重启手机之后好了

**Comment by zhinitm** [comment]
椒盐音乐好像无法显示歌词

**Comment by xiaowine** [comment]
@zhinitm 椒盐未更新api

**Comment by Zhan-Yu-Xi** [comment]
大佬我记得以前好像有歌词时可以自动关闭显示实时网速的，现在怎么没有了，可不可以加回来。还有现在咪咕音乐无效了，另外我发现了一个bug，就是有时候歌词会突然显示歌曲的名字，而不是它原本的歌词。

**Comment by xiaowine** [comment]
@Zhan-Yu-Xi 新版咪咕把魅族状态栏歌词删除了，已近无法使用了

**Comment by Pennages** [comment]
能够加入多个hook点么？除了状态栏上，QS快速设置上也想设置一个🤤

**Comment by xiaowine** [comment]
@Pennages 一个view只能添加在一个地方，如果要在多个地方显示，那么管理就麻烦

**Comment by weaponmasterjax** [comment]
> 椒盐音乐好像无法显示歌词

把设置里面xposed的状态栏歌词关掉，选择系统级即可

**Comment by zbdhdb** [comment]
什么时候支持大白鲨音乐

**Comment by 3310129921** [comment]
运营商和时间隐藏不彻底有bug，小米手机向下滑后会显示

**Comment by klxiaoniu** [comment]
@3310129921 打开限制可见性更改

**Comment by ZaiDAP** [comment]
怎么都不显示歌词……
测试模式下获取 Hook 是正常的，出现 App 名称并且时间隐藏；关掉测试模式重启就什么都不显示了。
Lyrics Getter 也已经勾选音乐 App
![Screenshot_20230716-133517_墨-状态栏歌词](https://github.com/Block-Network/StatusBarLyric/assets/41657393/54debc53-3aa6-4001-a3ff-9b2eb80ce049)
![Screenshot_20230716-135204_Shell](https://github.com/Block-Network/StatusBarLyric/assets/41657393/a9af416f-8be3-40cd-b1b4-f155a33a6275)
![Screenshot_20230716-135151_Shell](https://github.com/Block-Network/StatusBarLyric/assets/41657393/0a977552-8107-4e69-a066-7b47c164c9ee)
没有重构的版本是能显示的

**Comment by Demon-Lucifer** [comment]
MIUI14，没有隐藏网速了吗，5.几是有的

**Comment by ZaiDAP** [comment]
这是一封自动回复邮件。
已经收到您的来信，我会尽快回复。
                                                   ZaiDAP

**Comment by GodGun968** [comment]
点击 重启SystemUI 无效， SystemUI 不会重启

**Comment by GodGun968** [comment]
用Cemiuiler等模块可以重启系统界面

**Comment by Demon-Lucifer** [comment]
之前有防烧瓶选项，现在是默认开启还是功能没转移完全😶

**Comment by panzengjin** [comment]
不能重启systemui是因为你们没给root权限

**Comment by GodGun968** [comment]
> 不能重启systemui是因为你们没给root权限

谢谢，这上面没个要root的提示，我以为不用呢w

**Comment by Aircae** [comment]
> 椒盐音乐好像无法显示歌词

把  系统级状态栏歌词  打开  ，xposed状态栏歌词 开了没用

**Comment by PRO-2684** [comment]
歌词移动速度有没有可能做成自适应，就是根据这句歌词的持续时长来决定移动速度

**Comment by Floating-clouds-923306870** [comment]
QQ音乐的歌词显示会经常突然出现歌曲名，等下一句歌词出来后才能恢复 网易云没这个问题
能不能把点击后切换时间显示的功能加回来😍
最后问一下这个版本的会烧屏吗

**Comment by C-neon** [comment]
大佬，旧版有一个功能是延迟隐藏歌词，就那个隔一段时间自动隐藏歌词的选项现在没了，但还是挺有用的🥺
比如说从有歌词的音乐切到没歌词的音乐的时候，上一首的歌词还在那里一直挂着不动直到暂停
或者默认让每次切歌时候自动清空一下歌词也可以的🥹

**Comment by MoGuangYu** [comment]
切换浅/深色模式就失效得重启systemui，失效不显示歌词，连时间都不显示了..

**Comment by xiaowine** [comment]
@MoGuangYu miui特性

**Comment by MoGuangYu** [comment]
> @MoGuangYu miui特性

貌似以前版本并不会这样

**Comment by Raerl** [comment]
发现了几个小bug，一个是当时间切换到歌词时会出现歌词只显示一点点然后才显示完整，还有一个就是切换到深色模式后歌词直接消失只剩下时间，关闭深色模式也没用必须重启，不知道这个全新版本有没有防烧屏功能
![IMG_20230717_151518](https://github.com/Block-Network/StatusBarLyric/assets/76389548/b62923a4-5545-4273-a319-82bc4a99c6ad)
![IMG_20230717_151535](https://github.com/Block-Network/StatusBarLyric/assets/76389548/d1a09447-df42-422b-b3c4-3e073773823b)

**Comment by Duster-Cule** [comment]
获取Hook点时显示广播接收超时
主开关已经开启，已经给予软件root权限
Lyric Getter和状态栏歌词app均正常安装并启用推荐作用域
重启SystemUI，重启手机都尝试过了，还是不行
(老版本状态栏歌词可以正常显示)

模块版本：6.0.0(200)-release
模块构建时间: 2023-7-15 17:10
系统:Android 13(API 33), MIUI 14.0.3
手机型号:Redmi Note 11T pro
LSPosed: API版本 93, 框架/管理器版本 1.8.6(6712)
系统架构:arm64-v8a

**Comment by xiaowine** [comment]
@Duster-Cule 升级lsp

**Comment by Howard20181** [comment]
@Duster-Cule 不是
用CI版

**Comment by forchannot** [comment]
> QQ音乐的歌词显示会经常突然出现歌曲名，等下一句歌词出来后才能恢复 网易云没这个问题
> 能不能把点击后切换时间显示的功能加回来😍
> 最后问一下这个版本的会烧屏吗

+1，QQ音乐经常莫名其妙出现歌曲名，回退5.x版本后正常

**Comment by RifleNoob233** [comment]
模块版本：6.0.0(200)-release
模块构建时间: 2023-7-15 17:10
系统:Android 13（API 33）MIUI 14.0.29.0（TMCCNXM）
手机型号:Xiaomi 13,12+256G
LSPosed: API版本 100, 框架/管理器版本 1.8.6(6940)
系统架构:arm64-v8a

Lyric Getter 版本1.0.4.4-.6，经测试状态栏歌词可以正常显示，但在状态栏歌词面板内则显示没有支持的版本的Lyric Getter。墨息则正常检测到Lyric Getter

**Comment by xiaowine** [comment]
> 模块版本：6.0.0(200)-release
> 模块构建时间: 2023-7-15 17:10
> 系统:Android 13（API 33）MIUI 14.0.29.0（TMCCNXM）
> 手机型号:Xiaomi 13,12+256G
> LSPosed: API版本 100, 框架/管理器版本 1.8.6(6940)
> 系统架构:arm64-v8a
> 
> Lyric Getter 版本1.0.4.4-.6，经测试状态栏歌词可以正常显示，但在状态栏歌词面板内则显示没有支持的版本的Lyric Getter。墨息则正常检测到Lyric Getter

已经6.0.1了

**Comment by baimo2333** [comment]
你好，网速不能隐藏啊，暂时只能用占满宽度让网速隐藏；另外椒盐播放音乐时，歌词不会出现，只有在重启一遍systemUI后才会出现歌词

**Comment by baimo2333** [comment]
你好，网速不能隐藏啊，暂时只能用占满宽度让网速隐藏；另外椒盐播放音乐时，歌词不会出现，只有在重启一遍systemUI后才会出现歌词

**Comment by 0309Hj** [comment]
你们会不会在听歌的时候点开微信语音，然后状态栏歌词就不显示了，需要重新重启SystemUI才能生效，感觉怪怪的

**Comment by AwuTakeru** [comment]
现在自动隐藏图标不生效了，另外隐藏网速和点击切换时间还会有吗

**Comment by Chen593703392** [comment]
> 经过一段时间的重写，《墨-状态栏歌词》已经全部重构，现在的版本相比以前的版本，更加的省电，性能占用更加的少，系统通用性更高，几乎适配所有系统。并且将获取歌词部分单独拎出来，作为单独的模块，以后可以单独更新，两者互不影响。 现在我来简单介绍新版使用方法。首先打开LSPOSED框架，激活《墨-状态栏歌词》与《Lyric Getter》这两个模块，作用域默认推荐应用即可。 之后我们打开《墨-状态栏歌词》进行配置。首先打开主开关，切记一定要打开，否则后面的所有功能将无法生效。之后再打开Hook页，打开测试模式选项，重启SystemUI，重启后点击获取Hook点，不出意外将出现一个列表。这就是模块粗略筛选后得出的结果，选择一个Hook点中作为使用的Hook点。（当状态栏出现模块名字并且时间消失则为可用的Hook点）选择后关闭测试模式，再次重启SystemUI。 到此《墨-状态栏歌词》的基础配置完成，在音乐软件内打开对应功能即可在状态栏显示歌词，要开启哪些功能可以参考[此网页](https://github.com/xiaowine/Lyric-Getter)

**Comment by Chen593703392** [comment]
两个模块下了 重启了手机 主开关也打开了 目前无法显示歌词 状态栏能成功显示模块名字 墨状态歌词里面 显示 没有支持的版本的lc getter 网易云版本和模块均为最新

**Comment by xiaowine** [comment]
> 怎么都不显示歌词……
> 测试模式下获取 Hook 是正常的，出现 App 名称并且时间隐藏；关掉测试模式重启就什么都不显示了。
> Lyrics Getter 也已经勾选音乐 App
> ![Screenshot_20230716-133517_墨-状态栏歌词](https://github.com/Block-Network/StatusBarLyric/assets/41657393/54debc53-3aa6-4001-a3ff-9b2eb80ce049)
> ![Screenshot_20230716-135204_Shell](https://github.com/Block-Network/StatusBarLyric/assets/41657393/a9af416f-8be3-40cd-b1b4-f155a33a6275)
> ![Screenshot_20230716-135151_Shell](https://github.com/Block-Network/StatusBarLyric/assets/41657393/0a977552-8107-4e69-a066-7b47c164c9ee)
> 没有重构的版本是能显示的

检查lsp

**Comment by xiaowine** [comment]
> 之前有防烧瓶选项，现在是默认开启还是功能没转移完全😶

不需要了

**Comment by xiaowine** [comment]
> 两个模块下了 重启了手机 主开关也打开了 目前无法显示歌词 状态栏能成功显示模块名字 墨状态歌词里面 显示 没有支持的版本的lc getter 网易云版本和模块均为最新

升级lyric getter

**Comment by Chen593703392** [comment]
> > 两个模块下了 重启了手机 主开关也打开了 目前无法显示歌词 状态栏能成功显示模块名字 墨状态歌词里面 显示 没有支持的版本的lc getter 网易云版本和模块均为最新
> 
> 升级lyric getter

草 没给root权限 一直点的取消 2333

**Comment by Chen593703392** [comment]
> > 两个模块下了 重启了手机 主开关也打开了 目前无法显示歌词 状态栏能成功显示模块名字 墨状态歌词里面 显示 没有支持的版本的lc getter 网易云版本和模块均为最新
> 
> 升级lyric getter

不过升级之后真的好看 比原来好多了

**Comment by rchdliang** [comment]
旧版能正常显示歌词，更新大版本后无法显示歌词。
打开主开关，成功获取Hook点，能检测到Lyrics Getter, 始终允许获取应用列表，状态栏显示“墨-状态栏歌词”（勾选了限制可见性更改，但是时间变化时仍会重新显示时间），两个模块的lsp作用域均勾选了椒盐音乐和系统界面，并在ksu中均授予root权限，椒盐音乐中打开Xposed Lyric-Getter (API 4)开关
模块版本：6.0.1(201)-release
模块构建时间：2023-7-18 20:16
Lyrics Getter版本：1.0.44
椒盐音乐版本：8.13.0
系统：Android 13 (API 33) MIUI 14.0.11.0（TLKCNXM)
手机型号：Redmi K50 Pro, 12+256G
LSPosed: API版本 100，框架/管理器版本1.8.6(6941) - Zygisk, 启用Xposed API 调用保护，支持Dex优化器包装
系统架构：arm64-v8a
KernelSU版本：v0.6.2(11089)
Zygisk on KernelSU版本：v4-0.7.1 (89-release)

**Comment by xiaowine** [comment]
@rchdliang 重启生效

**Comment by rchdliang** [comment]
> @rchdliang 重启生效

还真不是重启能解决的
我一开始就用不了，怀疑是ksu lsp zygisk各种版本太低，升级了一圈，重启，不行，又下了最新编译的lyrics getter，也不行，又关掉了chi mi这种对状态栏有影响的模块，重启，也不管用，所以才来issue下面留言

**Comment by C-neon** [comment]
旧版的点按切换时间和歌词现在还能设置吗

**Comment by xiaowine** [comment]
@rchdliang 这么多miui都能用，你用不了，加油排除问题吧

**Comment by xiaowine** [comment]
@C-neon 测试版已经添加回来了，并且不会影响通知栏下拉

**Comment by Huaji250** [comment]
你好，先说明此问题在以前的版本是没有的。安卓13miui14，深色模式切换就失效，得重启系统界面才能解决

**Comment by GenTort666** [comment]
刘海屏，hook点正好在刘海屏区域怎么办？ 
如下图所示，当不是单手模式后测试位点正好进刘海屏里头去了（![Screenshot_20230722-235551_墨-状态栏歌词.png](https://github.com/Block-Network/StatusBarLyric/assets/86411424/d029220e-b8a7-41eb-ae43-b76289904fc6)

**Comment by xiaowine** [comment]
@GenTort666 换hook点

**Comment by GenTort666** [comment]
> @GenTort666 换hook点

是这样的，hook点要么不是没有显示要么就是卡刘海（

**Comment by xiaowine** [comment]
@GenTort666 你时间就在哪个位置吧

**Comment by GenTort666** [comment]
> @GenTort666 你时间就在哪个位置吧

屏幕的左上角
（有没有可能是改DPI让系统认为手机是平板了）

**Comment by C-neon** [comment]
> @C-neon 测试版已经添加回来了，并且不会影响通知栏下拉

感谢大佬

**Comment by C-neon** [comment]
> @C-neon 测试版已经添加回来了，并且不会影响通知栏下拉
感谢大佬🥹还有个小问题就是切歌时要是下一首没歌词，那上一首的歌词会一直扒着

**Comment by C-neon** [comment]
> @C-neon 测试版已经添加回来了，并且不会影响通知栏下拉

感谢大佬🥹还有个小问题就是切歌时要是下一首没歌词，那上一首的歌词会一直扒着

**Comment by xyang016** [comment]
有个bug，暂停或者关闭音乐播放器的时候，状态栏歌词不会消失，要重启系统界面才会消失

**Comment by sayainchina** [comment]
报告一个不算BUG的BUG，我更新以后，歌词的字体好像自动加粗了一样，非常不习惯

**Comment by xiaowine** [comment]
@sayainchina 可以自己跳呀，画笔宽度

**Comment by s-yh-china** [comment]
佬，在LineageOS 20.0的情况下，就算开了限制可见性更改。在有通知弹出的时候，通知信息会在歌词下面显示，并且时间会重新出现。

**Comment by rchdliang** [comment]
> @rchdliang 这么多miui都能用，你用不了，加油排除问题吧

1.0.5.4版lyrics getter升级后已经可用
顺带一提，状态栏显示网速，当歌词长度较短时，会在歌词末尾显示网速，这个目前有办法通过改边界距离宽度之类隐藏掉网速的显示吗，或者自动在歌词末尾加上可变长度的空格用于占位？

**Comment by xiaowine** [comment]
@rchdliang 有没有可能呀，你说的这些都有
