### ISSUE TITLE
更新新版后双卡状态下只能显示前一个运营商

### ISSUE THREAD

**Issue by houseyqh** [Block-Network/StatusBarLyric#327]
![Screenshot_2023-07-17-10-30-58-528_com android chrome](https://github.com/Block-Network/StatusBarLyric/assets/60042714/79f7935a-65b8-4396-a09c-80a6345913c5)
如题，机型k60pro，系统miui 14.0.23，旧版是可以正常显示两个运营商的
![Screenshot_2023-07-17-10-31-58-490_com miui home](https://github.com/Block-Network/StatusBarLyric/assets/60042714/28973cea-2402-477b-b6b8-3e6ae8e2a4ec)

**Comment by houseyqh** [comment]
另外，尝试开关飞行模式，有概率恢复正常，但大概率是歌词直接失效

**Comment by xiaowine** [comment]
@houseyqh 从原理来说，模块并未对控制中心的运营商做手脚，所以并不是本模块问题
