### ISSUE TITLE
图标隐藏错误

### ISSUE THREAD

**Issue by Zywz955** [Block-Network/StatusBarLyric#336]
开启有歌词时隐藏图标选项 但谷歌就寝模式图标无法隐藏造成显示错误
![371689750348_ pic_hd](https://github.com/Block-Network/StatusBarLyric/assets/102498620/7968f60e-720d-4a07-b634-5dfce63d9298)
![381689750348_ pic](https://github.com/Block-Network/StatusBarLyric/assets/102498620/cd0afa8e-7324-445f-aeb8-5d0a60b847c9)

**Comment by xiaowine** [comment]
@Zywz955 要不你再看看那个开关写的是啥
