### ISSUE TITLE
通知栏图标无法隐藏

### ISSUE THREAD

**Issue by ZYseven** [Block-Network/StatusBarLyric#337]
状态栏通知图标无法隐藏，设置中有通知时自动隐藏图标已开启，xperia 5，android 13，还有这一版6.0相较于上一版的时间隐藏不是特别稳定，下滑打开通知栏后与收到信息后歌词显示会错位，望解决，一直支持作者！👍👍
![Uploading Screenshot_20230719-152706.png…]()

**Comment by xiaowine** [comment]
@ZYseven 自动隐藏图标重启生效，若还是无效，则系统进行了魔改

**Comment by ZYseven** [comment]
> @ZYseven自动隐藏图标重启生效，若还是无效，则系统进行了魔改

回复的好快😮，索尼的系统应该没有魔改过，原生安卓，那我重启一下试试，谢谢

**Comment by ZYseven** [comment]
> @ZYseven自动隐藏图标重启生效，若还是无效，则系统进行了魔改

重启后可以解决！只是现在下拉通知栏再关闭后，会出现应用通知栏图标显示，以及接收信息的时候，会出现错位的情况
