### ISSUE TITLE
安装吼无法查找lyric getter

### ISSUE THREAD

**Issue by XuanXue2008** [Block-Network/StatusBarLyric#338]
系统：MIUI13.0.6 Android：12
lsp：1.8.6 
我尝试了两个大小不一样的包都不行，在getter我也照样尝试，依然无效，退回至5.6版本正常，请问大佬这个是怎么回事捏？

**Comment by xiaowine** [comment]
@XuanXue2008 检查其他模块，已经隐藏

**Comment by xiaowine** [comment]
@XuanXue2008 检查其他模块
