### ISSUE TITLE
貌似和cemiuiler有冲突，也许不是这个项目的问题

### ISSUE THREAD

**Issue by zxluxi** [Block-Network/StatusBarLyric#339]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
改善一下可能的与cemiuiler有冲突，先开的这个项目，再启用cemiuiler，此项目失效（状态栏没歌词），停用cemiuiler，此项目正常，MIUI14
**Describe alternatives you've considered**

**Additional context**

**Comment by Suan-Nai6** [comment]
我更新完6.0重启系统界面然后就一直自动重启，自动救砖把模块全关了才恢复，然后一个一个试发现是cemiuiler的问题
