### ISSUE TITLE
旧版兼容的修改软件新版不兼容

### ISSUE THREAD

**Issue by HMwancheng** [Block-Network/StatusBarLyric#341]
因为作者有说在开启时，关闭状态栏修改的软件，所以这条不确定算不算bug，作者看着关吧awa

有尝试过新版[6.0.1]，已确认一切设置好的话，在原版状态栏下可用
（此处小吐槽，release里的最新版稳定版主体和最新版[简称LG]其实不能联合使用，需要测试版）

目前使用回旧版[5.4.1]，在使用米客（CustoMIUIzer）修改状态栏后仍然可以正常使用（可以替换时间，覆盖后续图标等），但在新版里失效，无论是在原版状态栏下锚点还是修改后锚点，都无法在修改后的状态栏显示。
（此处小疑问，为什么旧版不需要手动选择呢，或者说旧版的自动识别其实很准？但是新版没法移植吗）

**Comment by duckiprepaid** [comment]
旧版兼容的软件，新版不兼容，老问题了，不更新养老呗
