### ISSUE TITLE
有个bug，暂停或者关闭音乐播放器的时候，状态栏歌词不会消失，要重启系统界面才会消失

### ISSUE THREAD

**Issue by xyang016** [Block-Network/StatusBarLyric#344]
有个bug，暂停或者关闭音乐播放器的时候，状态栏歌词不会消失，要重启系统界面才会消失

**Comment by xiaowine** [comment]
@xyang016 什么系统，什么音乐软件

**Comment by xyang016** [comment]
> @xyang016 什么系统，什么音乐软件
MIUI14，网易云8.10.30

**Comment by xyang016** [comment]
> @xyang016 什么系统，什么音乐软件
对了，能不能加个有歌词的时候通知图标或者网速消失的功能

**Comment by xiaowine** [comment]
@xyang016 去网易云设置把通知样式改为系统样式，我READEM写了

**Comment by xiaowine** [comment]
@xyang016 图标隐藏也有了呀，你能不能先去看看

**Comment by xyang016** [comment]
解决了！！！不好意思，图标我忘记开了，感谢你，那个有歌词的时候网速消失的功能，能加上吗，MIUI居中挖孔网速在左有歌词不消失很苦恼

**Comment by xiaowine** [comment]
@xyang016 不想加，没通用性。侧面解决方法就是调宽度，把它刚好遮住
