### ISSUE TITLE
Need to Restart SystemUI After Switching Dark / Light Mode

### ISSUE THREAD

**Issue by Bluevect** [Block-Network/StatusBarLyric#348]
**Describe the bug**
The lyric on the status bar disappears every time a switch of dark / light mode (in system settings) is done. It means that it is necessary to restart SystemUI after switching dark / light mode to get the lyric working again.

I don't know if this quite counts a bug, but here it is :) It does not influence a lot, but it was more perfect to get this tiny thing fixed!

Still, appreciate for your hard work!

**To Reproduce**
1. Play some music to test if the lyric works
2. Go to system settings and switch dark / light mode
3. See error (lyric disappears)
4. Go to the app and restart SystemUI and the lyric is back again

**Expected behavior**
The lyric on the status bar disappears every time a switch of dark / light mode (in system settings) is done.

**Screenshots**
Will provide if screenshots are actually needed :)

**Smartphone (please complete the following information):**
 - Device: Redmi K50 Pro (matisse)
 - OS: MIUI 14.0.12 (Stable, China ROM)
 - App Version: 6.0.1(201)-release

**Comment by xiaowine** [comment]
@Bluevect There is currently no solution to this problem, and it mostly occurs on custom systems

**Comment by Bluevect** [comment]
> @Bluevect There is currently no solution to this problem, and it mostly occurs on custom systems

Oh alright :) Just fix this when you have ideas for this!

**Comment by cxzlw** [comment]
> @Bluevect There is currently no solution to this problem, and it mostly occurs on custom systems

之前的版本是怎么做到的

**Comment by xiaowine** [comment]
> > @Bluevect There is currently no solution to this problem, and it mostly occurs on custom systems目前没有解决此问题的方法，它主要发生在自定义系统上
> 
> 之前的版本是怎么做到的
https://github.com/Block-Network/StatusBarLyric/tree/5.4.2v165
