### ISSUE TITLE
有没有可能阻止应用隐藏状态栏

### ISSUE THREAD

**Issue by Eric-Joker** [Block-Network/StatusBarLyric#349]
**Is your feature request related to a problem? Please describe.**
有些应用会隐藏状态栏，那就看不到歌词了

**Describe the solution you'd like**
有没有可能阻止隐藏状态栏并只隐藏其他部分，状态栏背景也设为透明

**Describe alternatives you've considered**
nothing

**Additional context**
nothing

**Comment by 2315506431** [comment]
如果这样的话，会更复杂，还要黑名单，不然你玩游戏什么的也会有，状态栏歌词之所以是状态栏歌词就是寄生在状态栏上，你又要强制显示状态栏不就和直接显示在屏幕顶部没区别了吗

**Comment by 2315506431** [comment]
这个软件是负责把歌词寄生在状态栏上的，至于状态栏是否显示你或许应该去别的软件
