### ISSUE TITLE
修改歌词字体的选项什么时候加回来

### ISSUE THREAD

**Issue by 2315506431** [Block-Network/StatusBarLyric#353]
之前可以改，改过的字体新版也继承了，但现在却没这个选项了

**Comment by xiaowine** [comment]
我在测试版就说了，不加ui，保留功能，要改手动移字体文件

**Comment by 2315506431** [comment]
文件的位置在哪啊，data里没有墨状态栏歌词，我懂一点但不多

**Comment by xiaowine** [comment]
> 文件的位置在哪啊，data里没有墨状态栏歌词，我懂一点但不多

加载路径 系统界面数据目录/files/font,font就是文件，固定名称。例如/data/user_de/0/com.android.systemui/files/font
