### ISSUE TITLE
歌词显示长短不一

### ISSUE THREAD

**Issue by xtchn** [Block-Network/StatusBarLyric#354]
**Describe the bug**
一首歌刚播放时，状态栏歌词长短限制得很短，播放一会儿后又能慢慢变长

**To Reproduce**
1.QQ音乐，正常自动切换歌曲或者手动切歌
2.QQ音乐切换到后台，观察状态栏

**Expected behavior**
状态栏歌词显示正常，长短固定

**Screenshots**
![Screenshot_2023-08-06-11-30-29-506_com.miui.mediaeditor.png](https://github.com/Block-Network/StatusBarLyric/assets/57317329/ad22badc-4c89-4f55-8ec6-27af1405ec6b)

如上图刚开始播放时歌词长度约两个汉字，后来慢慢边长到5个汉字，正常情况下应该是约10个汉字长度。

**Smartphone (please complete the following information):**
 - Device: 小米11ultra
 - OS: MIUI14
 - Version: 6.0.2

**Comment by xiaowine** [comment]
@xtchn 部分系统部分hook点是这样的，固定宽度解决

**Comment by xtchn** [comment]
可以了，谢谢！
