### ISSUE TITLE
广播接收超时

### ISSUE THREAD

**Issue by Sakitami** [Block-Network/StatusBarLyric#355]
**Describe the bug**
广播接收超时，无法获取Hook点

**To Reproduce**
1. 安装kernelsu，zygisk，lsposed。
2. 安装状态栏歌词模块，lyrics getter模块并勾选作用域。
3. 打开状态栏歌词模块，点击总开关，点击hook页，打开测试模式，重启系统界面，点击获取hook点。

**Expected behavior**
广播接收超时。

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ColorOS13.1 Android 14
 - KernelSU
 - Lsposed 1.8.6（6963）

**Smartphone (please complete the following information):**
 - Device: OnePlus 11 China
 - OS: ColorOS13.1 Android 14
 - KernelSU
 - Lsposed 1.8.6（6963）

**Additional context**

系统界面Apk：[cowtransfer](https://cowtransfer.com/s/c32731d6576f48)
传输口令 1eortl

**Comment by xiaowine** [comment]
@Sakitami 换magisk，ksu问题不管
