### ISSUE TITLE
深色模式切换后状态栏歌词失效

### ISSUE THREAD

**Issue by Dusttear** [Block-Network/StatusBarLyric#369]
红米k50
安卓13    miui 14.0.7
之前的版本切换深色模式不会有这个问题，这是新版本特性还是bug，希望能修复，要不每次都要重启状态栏，辛苦作者大大！

**Comment by Dusttear** [comment]
刚看到，，，


为什么有的时候用不了，需要重启系统界面
大概率是因为你切换在浅色/深色模式中切换了，由于部分系统玄学，导致功能失效，目前无法修复（已知MIUI和LG有这问题）

**Comment by xiaowine** [comment]
@Dusttear 已经有一个iss了，重复的我关了
