### ISSUE TITLE
修改主题时疑似会使hook失效，能否添加相关提示

### ISSUE THREAD

**Issue by Error-106** [Block-Network/StatusBarLyric#370]
发现修改主题时疑似会使hook失效，能否添加相关提示
Redmi Note 12 Pro+ MiUi 14.0.9

**Comment by Error-106** [comment]
在hook界面加行提示吧,我改息屏界面然后状态栏失效了找半天原因

**Comment by xiaowine** [comment]
> 在hook界面加行提示吧,我改息屏界面然后状态栏失效了找半天原因

不好加
