### ISSUE TITLE
深色模式切换支持

### ISSUE THREAD

**Issue by Error-106** [Block-Network/StatusBarLyric#372]
能否尝试对深色模式切换提供支持(例如允许用户选择两个hook点)

**Comment by xiaowine** [comment]
@Error-106 俩hook从数据上看，是一样的，理论也应该是一样的

**Comment by Error-106** [comment]
貌似确实是

**Comment by Error-106** [comment]
卡了个bug
![Screenshot_2023-10-01-10-28-06-111_com.netease.cloudmusic.jpg](https://github.com/Block-Network/StatusBarLyric/assets/92155028/3cc5ec29-da2a-441e-977d-0328a89e03f9)

**Comment by xiaowine** [comment]
@Error-106 触发情况，以及版本（精确到编译时间）

**Comment by Error-106** [comment]
这应该是MIUI的bug，系统界面实际上是浅色模式，但是依旧显示处于深色模式

**Comment by Error-106** [comment]
有可能获取到系统切换深色模式的信号然后跟随系统切换颜色吗

**Comment by xiaowine** [comment]
@Error-106 是这样写的，但是在部分系统上异常（模块内共有俩方案，可切换）

**Comment by Error-106** [comment]
我切换深色模式的时候会说更改了外观然后自动关闭

**Comment by Error-106** [comment]
![Screenshot_2023-10-01-13-19-38-984_com.miui.home.jpg](https://github.com/Block-Network/StatusBarLyric/assets/92155028/8b1393c5-31c7-4c01-bd3e-f807aced1162)

**Comment by xiaowine** [comment]
@Error-106 az，最近一条我理解错了
