### ISSUE TITLE
翻译和歌词分开显示

### ISSUE THREAD

**Issue by murasame520** [Block-Network/StatusBarLyric#387]
可以把翻译放左边，歌词放右边，或者反过来，挖孔屏真需要这个，歌词挤一堆

**Comment by RedSTARO** [comment]
@murasame520 附议

**Comment by xiaowine** [comment]
@murasame520 区分不出是歌词还是翻译

**Comment by RedSTARO** [comment]
可以像网速一样双行

**Comment by VictorModi** [comment]
@RedSTARO 双行歌词我曾在Lyrics Getter Ext尝试过，但无法在状态栏中正常显示换行符，在状态栏中换行符将会变成方块。而在 墨•息 中能够正常显示

**Comment by VictorModi** [comment]
@RedSTARO 双行歌词我曾在Lyrics Getter Ext尝试过，但无法在状态栏中正常显示换行符，在状态栏中换行符将会变成方块。而在 墨•息 中能够正常显示
