### ISSUE TITLE
MIUI隐藏网速失效

### ISSUE THREAD

**Issue by murasame520** [Block-Network/StatusBarLyric#388]
MIUI12.5.16的MIUI隐藏网速功能不管用

**Comment by xiaowine** [comment]
@murasame520 所以日志

**Comment by Giorie** [comment]
同MIUI12.5 网速显示去不掉 请问日志文件在哪里可以找到？两个模块都需要debug版么

**Comment by xiaowine** [comment]
@Giorie 本模块debug版本即可，日志在lsp里

**Comment by Giorie** [comment]
> @Giorie 本模块debug版本即可，日志在lsp里

[LSPosed_2023-11-09T16_01_11.624.zip](https://github.com/Block-Network/StatusBarLyric/files/13305400/LSPosed_2023-11-09T16_01_11.624.zip)
截取了从打开网易云开始播放音乐的一部分日志，感觉看不出有什么问题

**Comment by xiaowine** [comment]
@Giorie 重启界面仔

**Comment by Giorie** [comment]
> @Giorie 重启界面一次

似乎没有变化
[LSPosed_2023-11-09T16_11_09.759.zip](https://github.com/Block-Network/StatusBarLyric/files/13305526/LSPosed_2023-11-09T16_11_09.759.zip)
