### ISSUE TITLE
能否将歌词居中显示

### ISSUE THREAD

**Issue by yangyang133** [Block-Network/StatusBarLyric#391]
平板的状态栏很空，能否实现将歌词居中显示呢，现在的歌词显示在中线右边，显示有些局促
![Screenshot_20231107-214441](https://github.com/Block-Network/StatusBarLyric/assets/33922896/08188c2b-d57e-4289-b060-d347bd6fc822)

**Comment by yangyang133** [comment]
我这里有一个想法不知道是否可以实现：
平板作为一块完整的屏幕，中间没有刘海打孔等，并且状态栏比较空，一般状态栏分为左右两部分，我在想是否可以在状态栏中间新增一块区域，形成三个固定的区域，可以设置其比例为1：2：1，这样把歌词放在中间的部分居中显示，也不会影响原来的状态栏显示，不知道这样能否实现？

**Comment by xiaowine** [comment]
> 我这里有一个想法不知道是否可以实现： 平板作为一块完整的屏幕，中间没有刘海打孔等，并且状态栏比较空，一般状态栏分为左右两部分，我在想是否可以在状态栏中间新增一块区域，形成三个固定的区域，可以设置其比例为1：2：1，这样把歌词放在中间的部分居中显示，也不会影响原来的状态栏显示，不知道这样能否实现？

能实现，但是太复杂了，得不偿失

**Comment by yangyang133** [comment]
OK，感觉这样是对程序改动比较大
