### ISSUE TITLE
广播接收超时

### ISSUE THREAD

**Issue by MinecraftXFJ** [Block-Network/StatusBarLyric#399]
还没有适配 HyperOS 吗
https://xuefeng.lanzoub.com/iCl921go9zvc
Xiaomi HyperOS 1.0.23.11.19.DEV
Redmi K60

**Comment by xiaowine** [comment]
@MinecraftXFJ 先重启系统界面再点

**Comment by MinecraftXFJ** [comment]
> @MinecraftXFJ 先重启系统界面再点

已经重启，无效
放宽条件后也如此

**Comment by MinecraftXFJ** [comment]
> @MinecraftXFJ 先重启系统界面再点

已经重启，无效
放宽条件后也如此

**Comment by MinecraftXFJ** [comment]
> @MinecraftXFJ 请检查是否给予root，是否成功重启系统界面

确定已授予 root（Magisk Delta R6561D823-kitsune 26401） 并重启系统界面

**Comment by MinecraftXFJ** [comment]
> @MinecraftXFJ 反正已经有很多澎湃用上了

好吧，我再找找我的问题，打扰您了

**Comment by Shmily-zd** [comment]
请问找到原因吗，我也出现同样的问题
