### ISSUE TITLE
建议加一个控制日志输出的配置开关

### ISSUE THREAD

**Issue by grant-ymy** [Block-Network/StatusBarLyric#400]
音乐播放时会打印歌词到lsp的框架日志中。时间久了，会产生无用日志。建议加个配置项，可以控制是否打印歌词日志。

ps: 在小米13，HyperOS上使用时，切换到后台，会输出大量”change color“的日志。疑似状态栏颜色变化导致？？希望排查一下

**Comment by xiaowine** [comment]
@grant-ymy 只有debug才会产生日志，release并不会

**Comment by grant-ymy** [comment]
OK。是我安装成debug版本了。
