### ISSUE TITLE
BUG：歌词获取遗漏

### ISSUE THREAD

**Issue by wey-ie** [Block-Network/StatusBarLyric#403]
出现问题设备：小米手机
系统：HyperOS Android14
出现频率：必现
APP版本：6.1.2
Lyrics Getter版本：2.0.9
问题描述：每隔几句歌词就会漏掉一句不显示，间隔数量不定

**Comment by xiaowine** [comment]
@wey-ie 什么音乐软件

**Comment by wey-ie** [comment]
> @wey-ie 什么音乐软件

目前试了QQ音乐和网易云都有，其它没试

**Comment by wey-ie** [comment]
> @wey-ie什么音乐软件

目前试了QQ音乐和网易云，其它没试

**Comment by xiaowine** [comment]
@wey-ie 这俩软件目前无人反馈，我也无法复现

**Comment by wey-ie** [comment]
> @wey-ie 这俩软件目前无人反馈，我也无法复现


https://github.com/Block-Network/StatusBarLyric/assets/67129594/deaf54f0-6d79-408b-a0b8-7081e1516957

**Comment by wey-ie** [comment]
> @wey-ie 这俩软件目前无人反馈，我也无法复现

又测试了几次，最后发现网易云没有问题，有问题的是QQ音乐13.0及之后的版本，13.0之前的版本都正常，从13.0开始就会漏

**Comment by xiaowine** [comment]
@wey-ie 貌似是qq音乐的问题，因为获取歌词是通过魅族的状态栏接口获取的，如何模块确实歌词，那么魅族的也缺
