### ISSUE TITLE
歌词字体问题

### ISSUE THREAD

**Issue by EVAyo** [Block-Network/StatusBarLyric#404]
按 #353 中的目录在系统界面内找不到font文件夹,无法更改字体

设备:Realme GTNeo5

**Comment by xiaowine** [comment]
@EVAyo 看看目录

**Comment by xiaowine** [comment]
@EVAyo 刚想起来了，字体并不需要font目录

**Comment by xiaowine** [comment]
@EVAyo 你找一找closed的iss，有一条里面有
