### ISSUE TITLE
切换深色模式会导致系统界面重载

### ISSUE THREAD

**Issue by OnismIS** [Block-Network/StatusBarLyric#406]
每两次切换深色模式，100%触发系统界面重载，表现为黑屏后回到锁屏界面。测试在关闭本模块时问题消失，开启后即可稳定复现。

系统：HyperOS1.0.23.12.26.DEV
机型：Xiaomi 14
[LSPosed_2023-12-30T16_52_18.033648.zip](https://github.com/Block-Network/StatusBarLyric/files/13797606/LSPosed_2023-12-30T16_52_18.033648.zip)

https://github.com/Block-Network/StatusBarLyric/assets/119147710/a83cd52d-32b8-485a-bb3c-436ec577f461

**Comment by klxiaoniu** [comment]
重新选择hook点看一下。

**Comment by OnismIS** [comment]
> 重新选择hook点看一下。

解决了，多谢
