### ISSUE TITLE
无法hook到系统界面 尝试过许多次 lsposed优化也不行

### ISSUE THREAD

**Issue by toaltf4** [Block-Network/StatusBarLyric#411]
**Describe the bug**
无法hook到系统界面

在hook界面偶尔会显示 但大部分时候系统界面直接崩溃。

 - Device: 红米note12T
 - OS: Miui 14.0.25
 - 应用版本 6.1.3（206）

**Comment by toaltf4** [comment]
> **Describe the bug** 无法hook到系统界面
> 
> 在hook界面偶尔会显示 但大部分时候系统界面直接崩溃。
> 
> * Device: 红米note12T
> * OS: Miui 14.0.25
> * 应用版本 6.1.3（206）

系统界面链接
https://wwrh.lanzoul.com/iMkgp1lemjfi

**Comment by klxiaoniu** [comment]
没明白你的意思，详细描述一下你的操作

**Comment by toaltf4** [comment]
> 没明白你的意思，详细描述一下你的操作

![PixPin_2024-01-18_19-32-19](https://github.com/Block-Network/StatusBarLyric/assets/144699338/ff0174b1-3897-4a24-945e-d05cba68267b)

偶尔状态栏会出现字样，但通常系统界面此时会马上崩溃。
LSPosed除此软件外没有任何修改桌面的模块，尝试6.x教程文章Hook点都无法显示字样，_见gif_。

步骤：
1. 打开软件主界面；
2. 点击Hook页；
3. 重启系统界面并获取Hook点；（_放宽条件选项已开启_）
4. 选择页Hook点数量不定，通常4~6个，并且其中大部分Hook后会导致系统界面闪退（_见gif_），但是亦**无法在状态栏显示字样**以及**时钟无法消失**。
