### ISSUE TITLE
最新版本切换深色/浅色模式自动重启系统界面

### ISSUE THREAD

**Issue by Iniabi** [Block-Network/StatusBarLyric#412]
**Describe the bug**

最新版本切换深色/浅色模式自动重启系统界面。系统自动或手动切换也会重启，切换6.1.2无此类情况。

系统版本：hyperos 1.0.4.0
系统界面版本：20230316.0
lsposed日志：
![LSPosed_2024-01-18T18_47_22.119528.zip](https://github.com/Block-Network/StatusBarLyric/files/13975587/LSPosed_2024-01-18T18_47_22.119528.zip)

系统版本截图：
![Screenshot_2024-01-18-18-48-10-781_com.miui.securitycenter.jpg](https://github.com/Block-Network/StatusBarLyric/assets/134672413/904cbc7a-d4c0-4e87-a019-5759ee95dc1d)

系统界面apk：
![系统界面_20230316.0.zip](https://github.com/Block-Network/StatusBarLyric/files/13975603/_20230316.0.zip)

**Comment by klxiaoniu** [comment]
重新选择hook点试下

**Comment by Iniabi** [comment]
> 重新选择hook点试下

从6.1.2升级后，重新选择hook点发现只有一个hook点（放宽模式也只有一个） 重启系统界面后，问题未复现。以下为日志。
![LSPosed_2024-01-20T19_22_58.468696.zip](https://github.com/Block-Network/StatusBarLyric/files/13997688/LSPosed_2024-01-20T19_22_58.468696.zip)
