### ISSUE TITLE
請求適配blackplayer ex

### ISSUE THREAD

**Issue by 0316ng** [Block-Network/StatusBarLyric#431]
**Is your feature request related to a problem? Please describe.**
軟件名稱：BlackPlayer EX 20.62-407
很好用的一款本地播放器，希望您能在閒暇之餘幫忙適配，不勝感激，附上應用截圖和安裝包

**Additional context**
軟件詳情
![Screenshot_2024-05-06-17-18-41-057_com kodarkooperativet blackplayerex](https://github.com/Block-Network/StatusBarLyric/assets/61930381/42ec0b4c-02f5-4fe3-99b9-6627ee7d071d)
![Screenshot_2024-05-06-17-18-54-261_com kodarkooperativet blackplayerex](https://github.com/Block-Network/StatusBarLyric/assets/61930381/7e8494c5-5af1-4c88-b7b7-bdb91458d400)
[BlackPlayer EX [20.62].zip](https://github.com/Block-Network/StatusBarLyric/files/15218962/BlackPlayer.EX.20.62.zip)

**Comment by xiaowine** [comment]
https://github.com/xiaowine/Lyric-Getter
请来这个项目发送请求
