### ISSUE TITLE
软件使用教程中漏了一个步骤

### ISSUE THREAD

**Issue by xiaochen2002** [Block-Network/StatusBarLyric#445]
在6.x的软件使用教程里**有一个重要步骤没写进去**，就是“要在音乐软件里打开‘状态栏歌词’选项”，歌词才会正常显示（针对网易云来说，其他软件没试过）。
软件从5.x开始用的，当时教程应该有写，跟着教程做了于是软件在我的老手机上没问题。近一年前换新手机用了6.x，发现歌词怎么也不出来，跟着教程做了又做，软件，音乐重装了一次又一次，一度以为是系统方面的问题…直到今天无意间去翻网易云设置，看见了这个按钮，终于解决了大半年的困扰（笑哭）

**Screenshots**
![Screenshot_2024-08-29-14-34-49-720_com netease cloudmusic](https://github.com/user-attachments/assets/7b44d914-042b-4acf-ab3e-8ef155f816e0)

**Comment by 6ur9er** [comment]
> 在6.x的软件使用教程里**有一个重要步骤没写进去**，就是“要在音乐软件里打开‘状态栏歌词’选项”，歌词才会正常显示（针对网易云来说，其他软件没试过）。 软件从5.x开始用的，当时教程应该有写，跟着教程做了于是软件在我的老手机上没问题。近一年前换新手机用了6.x，发现歌词怎么也不出来，跟着教程做了又做，软件，音乐重装了一次又一次，一度以为是系统方面的问题…直到今天无意间去翻网易云设置，看见了这个按钮，终于解决了大半年的困扰（笑哭）
> 
> **Screenshots** ![Screenshot_2024-08-29-14-34-49-720_com netease cloudmusic](https://private-user-images.githubusercontent.com/47514706/362563658-7b44d914-042b-4acf-ab3e-8ef155f816e0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTc0NzIsIm5iZiI6MTcyNDkxNzE3MiwicGF0aCI6Ii80NzUxNDcwNi8zNjI1NjM2NTgtN2I0NGQ5MTQtMDQyYi00YWNmLWFiM2UtOGVmMTU1ZjgxNmUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA3MzkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxODRhN2E4MTJkNjE4ZTJkNDFkNDU3ZjFhNjU1M2NkYmYwYWRjMjI2OGZlOGUwYzViMmVmMDc1YWUzMjQ4Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c_QxuE_X-zQNcflmdqt9m4NOioq5dgoyUJhZHcoyBJo)

具体使用什么模式在 酒域-歌词获取 里有明确说明吧？
https://blog.xiaowine.cc/posts/32016/
比如低版本网易云需要的就是打开车载蓝牙歌词
![Screenshot_2024-08-29-15-35-19-022_cn lyric getter-edit](https://github.com/user-attachments/assets/1da1f5c4-6e18-452e-832e-916fd77448d8)
![Screenshot_2024-08-29-15-35-48-784_com netease cloudmusic](https://github.com/user-attachments/assets/ee387289-04dd-4c9c-88c1-41704f185927)

**Comment by xiaochen2002** [comment]
我是看到这个按钮后才茅塞顿开，我之前一直以为这个模式是在酒域-歌词获取里调的（然后怎么按都没反应hhh）
就是感觉…这个地方教程写的有点模糊，特别是像我这种理解力差的（x）
如果您感觉没问题就close吧
