### ISSUE TITLE
选锚点的时候重启系统界面

### ISSUE THREAD

**Issue by Wedingming** [Block-Network/StatusBarLyric#451]
**Describe the bug**
https://github.com/user-attachments/assets/01762c9c-1feb-49f9-a464-569c8ec279cf

第二次点“取消”后，实际上已经在重启系统界面了

**Desktop (please complete the following information):**
 - OS: 澎湃os 1.0.2.0 安卓13
 小米6

注：
先点一次，重进选锚点界面再点一次
点的两个不同
这些都会重启系统界面

**Comment by YuKongA** [comment]
无法复现
