### ISSUE TITLE
xposed 无法生效

### ISSUE THREAD

**Issue by ghhccghk** [Block-Network/StatusBarLyric#455]
**Screenshots**
![Screenshot_20240921-222803](https://github.com/user-attachments/assets/f1134cd7-7450-4164-a136-f3a25ed8de6e)

**Smartphone (please complete the following information):**
 - Device: Google pixel 6 pro
 - OS: 14 AP2A.240905.003.F1
 - Version 6.5.0

**Additional context**
日志文件
[LSPosed_2024-09-21T22_27_48.797861.zip](https://github.com/user-attachments/files/17084403/LSPosed_2024-09-21T22_27_48.797861.zip)

**Comment by qqlittleice233** [comment]
模块并不会支持非官方版LSPosed，或者请在官方版LSPosed测试后确认问题再进行反馈
