### ISSUE TITLE
歌词滚动过度

### ISSUE THREAD

**Issue by KingRootwang** [Block-Network/StatusBarLyric#460]
**Describe the bug**
歌词滚动到完全显示最后一个字后继续滚动，直到大约一半的歌词显示位置为空白后停止。

**To Reproduce**
1. 重启
2. 放歌
3. 100% 复现 bug
4. 但是，此时在`歌词样式`中任意调整部分设置（例如`歌词宽度`、`固定歌词宽度`、`歌词动画`等）后表现正常

**Expected behavior**
![Screenshot_20241003-162340_墨·状态栏歌词](https://github.com/user-attachments/assets/cf8daa93-3ef3-46c2-abea-9492fac89e70)

**Screenshots**
![Screenshot_20241003-161750](https://github.com/user-attachments/assets/57971fff-a350-4de0-ac7a-bcfb81eeff94)

**Desktop (please complete the following information):**
 - OS: `Android 13`
 - Browser `Chrome`
 - Version `129`

**Smartphone (please complete the following information):**
 - Device: `OnePlus 7 Pro`
 - OS: `Paranoid Android Topaz 7`, `Android 13`, `TKQ1.230915.002`
 - Browser 同上，虽然不知道有什么意义
 - 模块 Version `7.0.1`

**Additional context**

**Comment by KingRootwang** [comment]
看上去 7.0.0 没有这个问题

**Comment by YuKongA** [comment]
看了一下，因为 xiaowine 把 init 阶段的宽度计算给删掉了...
所以现在只有修改了配置后才会计算宽度。
xiaowine 全责

**Comment by xiaowine** [comment]
> 看了一下，因为 xiaowine 把 init 阶段的宽度计算给删掉了...
> 所以现在只有修改了配置后才会计算宽度。
> xiaowine 全责

但是init最后会调用changeConfig

**Comment by YuKongA** [comment]
> > 看了一下，因为 xiaowine 把 init 阶段的宽度计算给删掉了...
> > 所以现在只有修改了配置后才会计算宽度。
> > xiaowine 全责
> 
> 但是init最后会调用changeConfig

不在主线程
