### ISSUE TITLE
息屏下状态栏位置显示歌词

### ISSUE THREAD

**Issue by qiqiyaoc** [Block-Network/StatusBarLyric#461]
息屏下状态栏位置显示歌词

这个现象不知道是否为bug。
只有在关闭开关“锁定屏幕时隐藏歌词”才会发生。

预期结果：在锁屏保护界面状态栏显示歌词，息屏后不显示歌词。

实际结果：锁屏保护界面状态栏显示歌词，息屏后状态栏位置会有不再滚动的歌词，它会隔一段时间随着息屏显示上时间日期等信息的像素位置位移而刷新。

发生概率：时有时无，我也不能保证每次都有，但是多息屏几次就出来了。

版本：7.0.1
机型：RedmiK60pro，andriod14，hyper os 1.0.12

**Comment by xiaowine** [comment]
非bug
