### ISSUE TITLE
关于歌词与图标的左边距问题询问

### ISSUE THREAD

**Issue by sherkent** [Block-Network/StatusBarLyric#463]
之前的版本图标的左边距能调成负值，为何在最新7.0.1版本被删除了？

不知道是不是屏幕原因，状态栏显示的图标和歌词偏右（歌词和图标的左边有较大空白）

![Screenshot_2024-10-06-01-55-36-554_com.github.android-edit.jpg](https://github.com/user-attachments/assets/c5ed9baa-21e4-441a-9718-08b03444d81a)

之前的版本可以将左边距调成负值来纠正这个错误，现在却不行了

**Comment by xiaowine** [comment]
已经修改
