### ISSUE TITLE
请求增大图标左边距可选范围

### ISSUE THREAD

**Issue by iduee** [Block-Network/StatusBarLyric#464]
我是平板端用户，之前用的5.几版本，当时可以调整图标左边距使歌词大概位于屏幕中间，现在上限500还差不少才能到屏幕中间，请求增大图标左边距500的限制，和歌词左间距上限一样最大为2000。
![Screenshot_2024-10-08-17-59-37-398_statusbar lyric](https://github.com/user-attachments/assets/d5ef869c-3fcb-47c7-8288-f1aae9145a9f)

**Comment by xiaowine** [comment]
已经修改
