### ISSUE TITLE
歌词会覆盖平板的月日星期显示

### ISSUE THREAD

**Issue by iduee** [Block-Network/StatusBarLyric#465]
下图是没有播放音乐时状态栏的显示情况
![Screenshot_2024-10-08-18-21-46-344_com ss android ugc aweme](https://github.com/user-attachments/assets/81c343b2-0d02-4d90-b537-4516fe2f699f)
下面是最新版
![Screenshot_2024-10-08-18-20-17-957_statusbar lyric](https://github.com/user-attachments/assets/2db0fff5-507a-45f7-88c1-07c071611264)
上图:使用最新版时的显示情况，隐藏了 10月8日周二
![Screenshot_2024-10-08-18-21-10-279_statusbar lyric](https://github.com/user-attachments/assets/9146ae8a-0943-48ed-8dcc-80d62b987735)
上图:最新版自定义hook点只有一个能用，选择该点后还是会隐藏月日星期
更换5.4版本后显示如下
![Screenshot_2024-10-08-18-26-59-422_statusbar lyric](https://github.com/user-attachments/assets/ebf8ec4a-198a-4e9d-bb9d-54396428b0b7)

**Comment by xiaowine** [comment]
原理不同是这样的，并不是bug，你可以选择不隐藏时间

**Comment by iduee** [comment]
> 原理不同是这样的，并不是bug，你可以选择不隐藏时间

我选择了不隐藏时间，但是时分秒确实没有隐藏，但月日周会隐藏
