### ISSUE TITLE
在Android15上，模块无法被激活

### ISSUE THREAD

**Issue by 216592819** [Block-Network/StatusBarLyric#472]
系统 ColorOS 15
安卓版本为 Android 15
机型(可能需要): 一加12 PJD110

在安卓15版本中，
在LSPosed框架管理器中启用了模块 墨状态栏歌词。但是进入模块设置界面时，主开关无法打开，会提示:模块未激活。

由于LSPosed正式版本停止更新，我使用的LSPosed框架为分支版本: Jing Matrix
在使用这个分支版本时我的其他Xp模块均工作正常。我没有开启XposedApi调用保护。

你好，我在使用的设备是较新的安卓版本，所以上方信息只是为您提供一个可能的线索参考和问题反馈。也可能不太准确。
这是一个很棒的模块，如果可能，期待您的修复。:)

**Comment by xiaowine** [comment]
@216592819 lsp官方即将发布新版本

**Comment by 216592819** [comment]
感谢告知。蹲lsp更新...

**Comment by DuolaD** [comment]
可以先试试卸载重装最新Beta版，实测仅隐藏通知图标无法使用，其他正常。

设备:Xiaomi 15 A15 OS2 2.0.20.0

![Screenshot_2024-11-24-11-16-19-845_com.miui.home.jpg](https://github.com/user-attachments/assets/d7c91da1-6503-4f7d-a8a2-ad510de99f1d)

![Screenshot_2024-11-24-11-16-30-732_com.miui.home.jpg](https://github.com/user-attachments/assets/b5b7dd3b-0c23-4b72-90b7-7f5d0f3507c2)

**Comment by xiaowine** [comment]
请检查自己的lsp

**Comment by xiaowine** [comment]
实测lsp没问题，可以正常激活的
