### ISSUE TITLE
在 Xiaomi HyperOS 2 上与焦点通知冲突

### ISSUE THREAD

**Issue by Puppet357** [Block-Network/StatusBarLyric#477]
设备：Xiaomi 14
系统版本：OS2.0.6.0.VNCCNXM
软件版本：7.0.1

复现过程：播放音乐，显示状态栏歌词，若同时存在焦点通知，则状态栏歌词与焦点通知重叠

故障现象：
![Screenshot_2024-11-13-21-27-11-496_com netease cloudmusic](https://github.com/user-attachments/assets/16940d4e-a9de-4414-9e2c-4fba57022e72)

在开启“点按隐藏状态栏歌词”之后，点按状态栏歌词，可以恢复到正常显示时钟和焦点通知，能否在显示状态栏歌词的状态下，仅显示歌词，或是自动调整歌词右边距，避免与状态栏歌词重叠？

**Comment by Puppet357** [comment]
> #481

故障现象：问题依然存在，如下图
![Screenshot_2024-11-18-17-51-44-860_com netease cloudmusic](https://github.com/user-attachments/assets/f9fbf7bb-b4d7-4ee0-8533-7aca2d847f7b)

模块日志：使用debug版重启系统界面后抓取日志
[LSPosed_2024-11-18T17_52_09.421.zip](https://github.com/user-attachments/files/17798266/LSPosed_2024-11-18T17_52_09.421.zip)

**Comment by HChenX** [comment]
发行版尚未更新，请使用 Actions 构建的版本

**Comment by Puppet357** [comment]
> 发行版尚未更新，请使用 Actions 构建的版本

![Screenshot_2024-11-18-18-03-03-953_bin mt plus](https://github.com/user-attachments/assets/08dfd324-0aae-4073-9293-54b0fd086d5d)

使用的就是actions的版本

**Comment by HChenX** [comment]
#483
