### ISSUE TITLE
可以把歌词放在状态栏居中吗？

### ISSUE THREAD

**Issue by 160725** [Block-Network/StatusBarLyric#482]
平板放在左上角看起来有点难受

**Comment by xiaowine** [comment]
@160725 歌词跟随时间，你可以设置左边距强制向中间移动

**Comment by 160725** [comment]
我说的是像qq音乐的状态栏歌词这样，悬浮窗也行
歌词居中显示，其他都不变
![Screenshot_2024-11-18-00-02-06-937_com tencent qqmusic](https://github.com/user-attachments/assets/e4f8b894-501f-45d5-8ffd-12a0edacbefe)
