### ISSUE TITLE
悬浮标题

### ISSUE THREAD

**Issue by ghhccghk** [Block-Network/StatusBarLyric#487]
![Screenshot_20241124-153949](https://github.com/user-attachments/assets/2e0b1383-bb50-42b3-9f88-f0ea32344818)
**Describe the bug**
如图所示

**Smartphone (please complete the following information):**
 - Device:  小米 15
 - OS:  澎湃 2.0.20.0 安卓15
 - Version  7.0.1

**Comment by HChenX** [comment]
没遇到过
